## Challenge

In [1]:
import sys
import os
import numpy as np
import pandas as pd
import s3fs
import seaborn as sns
from collections import defaultdict
from dotenv import load_dotenv
project_root = '/home/onyxia/work/electera'
sys.path.insert(0, project_root)
from src.components.data_processing.data_loader import DataLoader
load_dotenv()

False

In [2]:
import os
import s3fs
os.environ["AWS_ACCESS_KEY_ID"] = 'XXXA4621E5RGRXZTKPF2'
os.environ["AWS_SECRET_ACCESS_KEY"] = '89rKPtUp0zK9KgK7KYiP0gMFSGewb3aCIL7p98Tt'
os.environ["AWS_SESSION_TOKEN"] = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJYWFhBNDYyMUU1UkdSWFpUS1BGMiIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzczNDAwMjgzLCJhenAiOiJvbnl4aWEiLCJjbmYiOnsiamt0IjoidEJITk9sZEdBYXFEdVJpZEgtVFUyT1lqa0RUN3o2LVdKclpES3gwVHA5USJ9LCJlbWFpbCI6ImFydGh1ci5tYW5jZWF1QHN0dWRlbnQtY3MuZnIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzc1MjA3NjE5LCJmYW1pbHlfbmFtZSI6Ik1hbmNlYXUiLCJnaXZlbl9uYW1lIjoiQXJ0aHVyIiwiZ3JvdXBzIjpbIlVTRVJfT05ZWElBIl0sImlhdCI6MTc3NDYwMjgxOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxhYi5zc3BjbG91ZC5mci9hdXRoL3JlYWxtcy9zc3BjbG91ZCIsImp0aSI6Im9ucnRydDpjOTNjNzJhYS1kZGYyLWViZmQtZWNhNi00Y2M4ZDIzMjM1NDYiLCJsb2NhbGUiOiJlbiIsIm5hbWUiOiJBcnRodXIgTWFuY2VhdSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhcnRodXJtYW5jZWF1IiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiJkYjViMDU0NC02NjA4LTU5NGItOGE0ZC1hMjkzMDZhNDRlZGEiLCJzdWIiOiJiYzc3Yjk3YS1lN2VkLTQ4ZWMtYmQ4Zi1lNzBjYjZhMTYyZGIiLCJ0eXAiOiJEUG9QIn0.TKYuZ6s1hiI0MH3GCWK5D4ZPndF_D4arI0UjNvJHVO4zLB2v_7XrCuq7Sx0O_pcPmPq4FjZX_Wdf8EOR8clgfQ'
os.environ["AWS_DEFAULT_REGION"] = 'us-east-1'
fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])

In [3]:
election_2014_t1 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm.parquet')
election_2014_t1['codecommune'] = election_2014_t1['codecommune'].replace({'01N01': '01283', '01N02': '01283'})
election_2014_t2 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm_t2.parquet')

election_2020_t1 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm.parquet')
election_2020_t2 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm_t2.parquet')

election_2026_t1 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm.parquet')
election_2026_t2 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm_t2.parquet')

2026-03-31 12:35:23.047 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm.parquet...
2026-03-31 12:35:23.456 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (36358, 63)
2026-03-31 12:35:23.535 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm_t2.parquet...
2026-03-31 12:35:23.819 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (1682, 63)
2026-03-31 12:35:23.858 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm.parquet...
2026-03-31 12:35:24.226 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (34768, 75)
2026-03-31 12:35:24.287 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm_t2.parquet...
2026-03-31 12:35:24.573 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (4524, 75)
2026-03-31 12:35:24.602 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm.parquet...
2026-03-31 12:35:24.972 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (34875, 75)
2026-03-31 12:35:25.025 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm_t2.parquet...
2026-03-31 12:35:25.318 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (1566, 73)

In [4]:
def clean_and_filter_dep(df):
    df['codecommune'] = df['codecommune'].astype(str).str.zfill(5)
    df['dep_num'] = df['dep'].replace({'A': 20.0, 'B': 20.0}, regex=True).astype(float)
    print("Before filter:", len(df))
    df = df[(df['dep_num'] <= 95.0) & (df['dep_num'] >= 1.0)]
    print("After filter:", len(df))
    return df

# Example usage for all datasets:
election_2014_t1 = clean_and_filter_dep(election_2014_t1)
election_2014_t2 = clean_and_filter_dep(election_2014_t2)
election_2020_t1 = clean_and_filter_dep(election_2020_t1)
election_2020_t2 = clean_and_filter_dep(election_2020_t2)
election_2026_t1 = clean_and_filter_dep(election_2026_t1)
election_2026_t2 = clean_and_filter_dep(election_2026_t2)

Before filter: 36358
After filter: 36358
Before filter: 1682
After filter: 1682
Before filter: 34768
After filter: 34768
Before filter: 4524
After filter: 4524
Before filter: 34875
After filter: 34711
Before filter: 1566
After filter: 1485

In [266]:
# Add year, tour, type columns
election_2014_t1['year'] = 2014
election_2014_t1['tour'] = 1
election_2014_t1['type'] = "muni"

election_2014_t2['year'] = 2014
election_2014_t2['tour'] = 2
election_2014_t2['type'] = "muni"

election_2020_t1['year'] = 2020
election_2020_t1['tour'] = 1
election_2020_t1['type'] = "muni"

election_2020_t2['year'] = 2020
election_2020_t2['tour'] = 2
election_2020_t2['type'] = "muni"

election_2026_t1['year'] = 2026
election_2026_t1['tour'] = 1
election_2026_t1['type'] = "muni"

election_2026_t2['year'] = 2026
election_2026_t2['tour'] = 2
election_2026_t2['type'] = "muni"

# Concatenate all datasets
elections = pd.concat([
    election_2014_t1, election_2014_t2,
    election_2020_t1, election_2020_t2,
    election_2026_t1, election_2026_t2
], axis=0)

In [6]:
socio_eco = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/derived/cache/dfc_cached.parquet')

2026-03-31 12:35:25.810 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/derived/cache/dfc_cached.parquet...

2026-03-31 12:36:12.081 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (38145, 31557)

In [124]:
cols_2019 = [col for col in socio_eco.columns if '2019' in col]

In [283]:
features = [
    'agesexcommunes/pop2014',
    'agesexcommunes/age2014',
    'cspcommunes/pagri2014',
    'cspcommunes/pindp2014',
    'cspcommunes/pcadr2014',
    'cspcommunes/ppint2014',
    'cspcommunes/pempl2014',
    'cspcommunes/pouvr2014',
    'cspcommunes/paind2014',
    'cspcommunes/paica2014',
    'cspcommunes/pouem2014',
    'cspcommunes/pcapi2014',
    'cspcommunes/pchom2014',
    'diplomescommunes/psup2014',
    'proprietairescommunes/ppropri2014',
    'popcommunesvbbm/vbbm2014',
    'popcommunesvbbm/vbbmpauvresriches2014',
    'pibcommunes/pibratio2014',
    'revcommunes/revratio2014', 
    'codecommune'
]

In [267]:
socio_eco_filtered = socio_eco[features].copy()
socio_eco_filtered['codecommune2026'] = socio_eco_filtered['codecommune'] 
# Drop rows where 'codecommune' is not 5 digits
socio_eco_filtered = socio_eco_filtered[socio_eco_filtered['codecommune'].astype(str).str.len() == 5]

In [268]:
passage = pd.read_csv('passage.csv').astype(str)
passage = passage.rename(columns={"CODGEO_INI": 'codecommune', "CODGEO_2026": 'codecommune2026'})
passage

      codecommune codecommune2026
0           01001           01001
1           01002           01002
2           01004           01004
3           01005           01005
4           01006           01006
...           ...             ...
36738       15141           15035
36739       15141           15047
36740       15141           15171
36741       76601           76601
36742       60054           60694

[36743 rows x 2 columns]

In [269]:
elections = elections.merge(passage, on='codecommune', how='left')
elections["codecommune2026"] = elections["codecommune2026"].fillna(elections['codecommune'])

In [272]:
data = elections.merge(socio_eco_filtered, on='codecommune2026', how='left', validate='m:1')

In [260]:
# Marseille arrondissement codes
marseille_codes = [
    "13201", "13202", "13203", "13204", "13205", "13206", "13207", "13208",
    "13209", "13210", "13211", "13212", "13213", "13214", "13215", "13216"
]

# Lyon arrondissement codes
lyon_codes = [
    "69381", "69382", "69383", "69384", "69386", "69387", "69388", "69389"
]

# Paris arrondissement codes
paris_codes = [
    "75101", "75102", "75103", "75104", "75105", "75106", "75107", "75108",
    "75109", "75110", "75111", "75112", "75113", "75114", "75115", "75116",
    "75117", "75118", "75119", "75120"
]

In [ ]:
# PLM

# Population
pop_col = "agesexcommunes/pop2014"
codecommune_col = 'codecommune2026'
data.loc[data[codecommune_col].isin(lyon_codes), pop_col] = data[data[codecommune_col].isin(lyon_codes)].fillna(data.loc[data[codecommune_col]=='69123', pop_col].sum()/9)
data.loc[data[codecommune_col].isin(marseille_codes),pop_col] = data[data[codecommune_col].isin(marseille_codes)].fillna(data.loc[data[codecommune_col]=='13055', pop_col].sum()/16)
data.loc[data[codecommune_col]=='75056', pop_col] = data[data[codecommune_col]=='75056'].fillna(data.loc[data[codecommune_col].isin(paris_codes), pop_col].sum())

# Other variables (all rates)
data.loc[data[codecommune_col].isin(lyon_codes), data[data[codecommune_col].isin(lyon_codes)].isna().any()] = data[data[codecommune_col].isin(lyon_codes)].fillna(data.loc[data[codecommune_col]=='69123', data[data[codecommune_col].isin(lyon_codes)].isna().any()].iloc[0])
data.loc[data[codecommune_col].isin(marseille_codes), data[data[codecommune_col].isin(marseille_codes)].isna().any()] = data[data[codecommune_col].isin(marseille_codes)].fillna(data.loc[data[codecommune_col]=='13055', data[data[codecommune_col].isin(marseille_codes)].isna().any()].iloc[0])
data.loc[data[codecommune_col]=='75056', data[data[codecommune_col]=='75056'].isna().any()] = data[data[codecommune_col]=='75056'].fillna(data.loc[data[codecommune_col].isin(paris_codes), data[data[codecommune_col]=='75056'].isna().any()].mean())

PB Paris sum

In [277]:
data.loc[data['codecommune2026']=='77393', ['tour', 'year', 'nb_list', 'pabs', pop_col]]

        tour  year  nb_list    pabs  agesexcommunes/pop2014
34809      1  2014      3.0  0.3180                  2823.0
46342      1  2020      1.0  0.7461                  2823.0
107620     1  2026      3.0  0.3993                  2823.0
113278     2  2026      2.0  0.3973                  2823.0

In [278]:
pol_col = [
    "pvote_LDVD","pvote_LFG","vote_LUD","vote_LFG","vote_LEXG","vote_LUG","pvote_LUD","vote_LEXD",
    "pvote_LUMP","vote_LUMP","pvote_LSOC","pvote_LEXD","pvote_LFN","vote_LDVD","vote_LDVG","vote_LSOC",
    "pvote_LDVG","pvote_LEXG","pvote_LUG","vote_LFN","vote_AUTRES","pvote_AUTRES","nb_list","voteG",
    "pvoteG","voteD","pvoteD","voteCD","pvoteCD","voteCG","pvoteCG","voteC","pvoteC","voteGCG",
    "voteDCD","voteTG","voteTD","pvoteGCG","pvoteDCD","pvoteTG","pvoteTD","ppar","pabs","pnulsi",
    "pnulsv","pblancsi","pblancsv","dep_num","year","tour","type","pvote_LFI","vote_LRN","vote_LDVC",
    "vote_LECO","pvote_LCOM","vote_LREM","vote_LUDI","pvote_LLR","vote_LUC","pvote_LRN","vote_LFI",
    "pvote_LUC","vote_LLR","vote_LCOM","pvote_LUDI","pvote_LREM","pvote_LDVC","pvote_LECO","pvote_LDSV",
    "vote_LDSV","vote_LUXD","pvote_LUXD"
]

In [279]:
data[pol_col] = data[pol_col].fillna(0.0)

In [280]:
data.isna().astype(int).sum().to_csv('missing.csv')

In [282]:
data.loc[data.isna().any(axis=1), :].to_csv('x.csv')

In [285]:
data.to_csv('final_data.csv')

- Taux de participation ajustée : 
    - Taux de participation sauf pour les communes avec une seule liste
    - Taux de vote pour un tendance : nombre de commune gagnées pondérés par le nombre

In [17]:
len(data[data['agesexcommunes/pop2018']<=1000]['codecommune'].unique())

26657

In [18]:
listes = data[(data['year']==2014)&(data['tour']==1)&(data['agesexcommunes/pop2018']<=1000)][['nb_list']]

In [19]:
(listes == 1.0).astype(int).sum()

nb_list    26306
dtype: int64

In [20]:
participation = data[(data['year']==2014)&(data['tour']==2)][['pvoteG', 'pvoteC', 'pvoteD', 'pvoteCD', 'pvoteCG']]

In [21]:
participation[(participation.max(axis=1)>0.5)].idxmax(axis=1).value_counts()

pvoteCD    452
pvoteCG    205
pvoteG      86
pvoteD       2
Name: count, dtype: int64