## Challenge

In [1]:
import sys
import os
import pandas as pd
import s3fs
from dotenv import load_dotenv

project_root = "/home/onyxia/work/electera"
sys.path.insert(0, project_root)
from src.components.data_processing.data_loader import DataLoader

load_dotenv()

False

In [2]:
os.environ["AWS_ACCESS_KEY_ID"] = "XXXA4621E5RGRXZTKPF2"
os.environ["AWS_SECRET_ACCESS_KEY"] = "89rKPtUp0zK9KgK7KYiP0gMFSGewb3aCIL7p98Tt"
os.environ["AWS_SESSION_TOKEN"] = (
    "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJYWFhBNDYyMUU1UkdSWFpUS1BGMiIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzczNDAwMjgzLCJhenAiOiJvbnl4aWEiLCJjbmYiOnsiamt0IjoidEJITk9sZEdBYXFEdVJpZEgtVFUyT1lqa0RUN3o2LVdKclpES3gwVHA5USJ9LCJlbWFpbCI6ImFydGh1ci5tYW5jZWF1QHN0dWRlbnQtY3MuZnIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzc1MjA3NjE5LCJmYW1pbHlfbmFtZSI6Ik1hbmNlYXUiLCJnaXZlbl9uYW1lIjoiQXJ0aHVyIiwiZ3JvdXBzIjpbIlVTRVJfT05ZWElBIl0sImlhdCI6MTc3NDYwMjgxOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxhYi5zc3BjbG91ZC5mci9hdXRoL3JlYWxtcy9zc3BjbG91ZCIsImp0aSI6Im9ucnRydDpjOTNjNzJhYS1kZGYyLWViZmQtZWNhNi00Y2M4ZDIzMjM1NDYiLCJsb2NhbGUiOiJlbiIsIm5hbWUiOiJBcnRodXIgTWFuY2VhdSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhcnRodXJtYW5jZWF1IiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiJkYjViMDU0NC02NjA4LTU5NGItOGE0ZC1hMjkzMDZhNDRlZGEiLCJzdWIiOiJiYzc3Yjk3YS1lN2VkLTQ4ZWMtYmQ4Zi1lNzBjYjZhMTYyZGIiLCJ0eXAiOiJEUG9QIn0.TKYuZ6s1hiI0MH3GCWK5D4ZPndF_D4arI0UjNvJHVO4zLB2v_7XrCuq7Sx0O_pcPmPq4FjZX_Wdf8EOR8clgfQ"
)
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
fs = s3fs.S3FileSystem(
    client_kwargs={"endpoint_url": "https://" + "minio.lab.sspcloud.fr"},
    key=os.environ["AWS_ACCESS_KEY_ID"],
    secret=os.environ["AWS_SECRET_ACCESS_KEY"],
    token=os.environ["AWS_SESSION_TOKEN"],
)

In [3]:
election_2014_t1 = DataLoader().load_dataset(
    "s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm.parquet"
)
election_2014_t1["codecommune"] = election_2014_t1["codecommune"].replace(
    {"01N01": "01283", "01N02": "01283"}
)
election_2014_t2 = DataLoader().load_dataset(
    "s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm_t2.parquet"
)

election_2020_t1 = DataLoader().load_dataset(
    "s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm.parquet"
)
election_2020_t2 = DataLoader().load_dataset(
    "s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm_t2.parquet"
)

election_2026_t1 = DataLoader().load_dataset(
    "s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm.parquet"
)
election_2026_t2 = DataLoader().load_dataset(
    "s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm_t2.parquet"
)

2026-04-01 05:23:49.193 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm.parquet...
2026-04-01 05:23:52.205 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (36358, 79)
2026-04-01 05:23:52.304 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm_t2.parquet...
2026-04-01 05:23:52.611 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (1682, 79)
2026-04-01 05:23:52.649 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm.parquet...
2026-04-01 05:23:53.099 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (34770, 77)
2026-04-01 05:23:53.164 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm_t2.parquet...
2026-04-01 05:23:53.475 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (4524, 77)
2026-04-01 05:23:53.500 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm.parquet...
2026-04-01 05:23:53.998 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (34876, 91)
2026-04-01 05:23:54.066 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm_t2.parquet...
2026-04-01 05:23:54.422 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (1566, 83)

In [4]:
def clean_and_filter_dep(df):
    df["codecommune"] = df["codecommune"].astype(str).str.zfill(5)
    df["dep_num"] = df["dep"].replace({"A": 20.0, "B": 20.0}, regex=True).astype(float)
    print("Before filter:", len(df))
    df = df[(df["dep_num"] <= 95.0) & (df["dep_num"] >= 1.0)]
    print("After filter:", len(df))
    return df


# Example usage for all datasets:
election_2014_t1 = clean_and_filter_dep(election_2014_t1)
election_2014_t2 = clean_and_filter_dep(election_2014_t2)
election_2020_t1 = clean_and_filter_dep(election_2020_t1)
election_2020_t2 = clean_and_filter_dep(election_2020_t2)
election_2026_t1 = clean_and_filter_dep(election_2026_t1)
election_2026_t2 = clean_and_filter_dep(election_2026_t2)

Before filter: 36358
After filter: 36358
Before filter: 1682
After filter: 1682
Before filter: 34770
After filter: 34770
Before filter: 4524
After filter: 4524
Before filter: 34876
After filter: 34712
Before filter: 1566
After filter: 1485

In [5]:
# Add year, tour, type columns
election_2014_t1["year"] = 2014
election_2014_t1["tour"] = 1
election_2014_t1["type"] = "muni"

election_2014_t2["year"] = 2014
election_2014_t2["tour"] = 2
election_2014_t2["type"] = "muni"

election_2020_t1["year"] = 2020
election_2020_t1["tour"] = 1
election_2020_t1["type"] = "muni"

election_2020_t2["year"] = 2020
election_2020_t2["tour"] = 2
election_2020_t2["type"] = "muni"

election_2026_t1["year"] = 2026
election_2026_t1["tour"] = 1
election_2026_t1["type"] = "muni"

election_2026_t2["year"] = 2026
election_2026_t2["tour"] = 2
election_2026_t2["type"] = "muni"

# Concatenate all datasets
elections = pd.concat(
    [
        election_2014_t1,
        election_2014_t2,
        election_2020_t1,
        election_2020_t2,
        election_2026_t1,
        election_2026_t2,
    ],
    axis=0,
)

In [6]:
socio_eco = DataLoader().load_dataset(
    "s3://arthurmanceau/election_modeling_uhcp/data/derived/cache/dfc_cached.parquet"
)

2026-04-01 05:23:55.447 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/derived/cache/dfc_cached.parquet...
2026-04-01 05:24:56.664 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (38145, 31557)

In [7]:
cols_2019 = [col for col in socio_eco.columns if "2019" in col]

In [8]:
features = [
    "agesexcommunes/pop2014",
    "agesexcommunes/age2014",
    "cspcommunes/pagri2014",
    "cspcommunes/pindp2014",
    "cspcommunes/pcadr2014",
    "cspcommunes/ppint2014",
    "cspcommunes/pempl2014",
    "cspcommunes/pouvr2014",
    "cspcommunes/paind2014",
    "cspcommunes/paica2014",
    "cspcommunes/pouem2014",
    "cspcommunes/pcapi2014",
    "cspcommunes/pchom2014",
    "diplomescommunes/psup2014",
    "proprietairescommunes/ppropri2014",
    "popcommunesvbbm/vbbm2014",
    "popcommunesvbbm/vbbmpauvresriches2014",
    "pibcommunes/pibratio2014",
    "revcommunes/revratio2014",
    "codecommune",
]

In [9]:
socio_eco_filtered = socio_eco[features].copy()
socio_eco_filtered["codecommune2026"] = socio_eco_filtered["codecommune"]
# Drop rows where 'codecommune' is not 5 digits
socio_eco_filtered = socio_eco_filtered[
    socio_eco_filtered["codecommune"].astype(str).str.len() == 5
]

In [10]:
passage = pd.read_csv("passage.csv").astype(str)
passage = passage.rename(
    columns={"CODGEO_INI": "codecommune", "CODGEO_2026": "codecommune2026"}
)
passage

      codecommune codecommune2026
0           01001           01001
1           01002           01002
2           01004           01004
3           01005           01005
4           01006           01006
...           ...             ...
36738       15141           15035
36739       15141           15047
36740       15141           15171
36741       76601           76601
36742       60054           60694

[36743 rows x 2 columns]

In [11]:
elections = elections.merge(passage, on="codecommune", how="left")
elections["codecommune2026"] = elections["codecommune2026"].fillna(
    elections["codecommune"]
)

In [12]:
data = elections.merge(
    socio_eco_filtered, on="codecommune2026", how="left", validate="m:1"
)

In [13]:
# Marseille arrondissement codes
marseille_codes = [
    "13201",
    "13202",
    "13203",
    "13204",
    "13205",
    "13206",
    "13207",
    "13208",
    "13209",
    "13210",
    "13211",
    "13212",
    "13213",
    "13214",
    "13215",
    "13216",
]

# Lyon arrondissement codes
lyon_codes = ["69381", "69382", "69383", "69384", "69386", "69387", "69388", "69389"]

# Paris arrondissement codes
paris_codes = [
    "75101",
    "75105",
    "75106",
    "75107",
    "75108",
    "75109",
    "75110",
    "75111",
    "75112",
    "75113",
    "75114",
    "75115",
    "75116",
    "75117",
    "75118",
    "75119",
    "75120",
]

In [14]:
tour = data["tour"].unique().tolist()
years = data["year"].unique().tolist()
tour, years

([1, 2], [2014, 2020, 2026])

In [15]:
pop_col = "agesexcommunes/pop2014"
codecommune_col = "codecommune2026"
# PLM
for t in tour:
    for y in years:
        data.loc[
            (data[codecommune_col].isin(lyon_codes))
            & (data["tour"] == t)
            & (data["year"] == y),
            pop_col,
        ] = data[
            (data[codecommune_col].isin(lyon_codes))
            & (data["tour"] == t)
            & (data["year"] == y)
        ].fillna(
            data.loc[
                (data[codecommune_col] == "69123")
                & (data["tour"] == 1)
                & (data["year"] == 2026),
                pop_col,
            ].sum()
            / 9
        )
        data.loc[
            (data[codecommune_col].isin(marseille_codes))
            & (data["tour"] == t)
            & (data["year"] == y),
            pop_col,
        ] = data[
            (data[codecommune_col].isin(marseille_codes))
            & (data["tour"] == t)
            & (data["year"] == y)
        ].fillna(
            data.loc[
                (data[codecommune_col] == "13055")
                & (data["tour"] == 1)
                & (data["year"] == 2026),
                pop_col,
            ].sum()
            / 16
        )
        data.loc[
            (data[codecommune_col] == "75056")
            & (data["tour"] == t)
            & (data["year"] == y),
            pop_col,
        ] = data[
            (data[codecommune_col] == "75056")
            & (data["tour"] == t)
            & (data["year"] == y)
        ].fillna(
            data.loc[
                (data[codecommune_col].isin(paris_codes))
                & (data["tour"] == 1)
                & (data["year"] == y),
                pop_col,
            ].sum()
        )

        # Other variables (all rates)
        data.loc[
            (data[codecommune_col].isin(lyon_codes))
            & (data["tour"] == t)
            & (data["year"] == y),
            data[data[codecommune_col].isin(lyon_codes)].isna().any(),
        ] = data[
            (data[codecommune_col].isin(lyon_codes))
            & (data["tour"] == t)
            & (data["year"] == y)
        ].fillna(
            data.loc[
                (data[codecommune_col] == "69123"),
                data[data[codecommune_col].isin(lyon_codes)].isna().any(),
            ].iloc[0]
        )
        data.loc[
            (data[codecommune_col].isin(marseille_codes))
            & (data["tour"] == t)
            & (data["year"] == y),
            data[(data[codecommune_col].isin(marseille_codes))].isna().any(),
        ] = data[
            (data[codecommune_col].isin(marseille_codes))
            & (data["tour"] == t)
            & (data["year"] == y)
        ].fillna(
            data.loc[
                (data[codecommune_col] == "13055"),
                data[data[codecommune_col].isin(marseille_codes)].isna().any(),
            ].iloc[0]
        )
        data.loc[
            (data[codecommune_col] == "75056")
            & (data["tour"] == t)
            & (data["year"] == y),
            data[data[codecommune_col] == "75056"].isna().any(),
        ] = data[
            (data[codecommune_col] == "75056")
            & (data["tour"] == t)
            & (data["year"] == y)
        ].fillna(
            data.loc[
                (data[codecommune_col].isin(paris_codes))
                & (data["tour"] == 1)
                & (data["year"] == y),
                data[data[codecommune_col] == "75056"].isna().any(),
            ].mean()
        )

In [16]:
data.loc[
    data["codecommune2026"] == "75056",
    ["tour", "nomcommune", "year", "nb_list", "pabs", pop_col],
]

        tour nomcommune  year  nb_list    pabs  agesexcommunes/pop2014
106541     1      Paris  2026      7.0  0.4111               2129751.0
113229     2      Paris  2026      3.0  0.3840               2129751.0

In [17]:
data.loc[
    data["codecommune2026"].isin(paris_codes),
    ["tour", "nomcommune", "year", "nb_list", "pabs", pop_col],
]

,tour,nomcommune,year,nb_list,pabs,agesexcommunes/pop2014
34445,1,Paris 1er arrondissement (secteur 1),2014,7.0,0.4039,16725.0
34449,1,Paris 5eme arrondissement (secteur 5),2014,7.0,0.3582,59775.0
34450,1,Paris 6eme arrondissement (secteur 6),2014,7.0,0.4120,42103.0
34451,1,Paris 7eme arrondissement (secteur 7),2014,6.0,0.4191,54591.0
34452,1,Paris 8eme arrondissement (secteur 8),2014,7.0,0.4424,38097.0
...,...,...,...,...,...,...
113626,2,Paris 14eme arrondissement (secteur 14),2026,2.0,0.3779,138351.0
113627,2,Paris 15eme arrondissement (secteur 15),2026,3.0,0.3721,235481.0
113628,2,Paris 18eme arrondissement (secteur 18),2026,4.0,0.4115,198280.0
113629,2,Paris 19eme arrondissement (secteur 19),2026,3.0,0.4479,186291.0
113630,2,Paris 20eme arrondissement (secteur 20),2026,3.0,0.4132,196558.0

In [18]:
data.loc[
    data["codecommune2026"].isin(marseille_codes),
    ["tour", "nomcommune", "year", "nb_list", "pabs", pop_col],
]

,tour,nomcommune,year,nb_list,pabs,agesexcommunes/pop2014
27559,1,Marseille 1er arrondissement (secteur 1),2014,7.0,0.4417,53600.125
27560,1,Marseille 7eme arrondissement (secteur 1),2014,7.0,0.4417,53600.125
27561,1,Marseille 2eme arrondissement (secteur 2),2014,7.0,0.5400,53600.125
27562,1,Marseille 3eme arrondissement (secteur 2),2014,7.0,0.5400,53600.125
27563,1,Marseille 5eme arrondissement (secteur 3),2014,7.0,0.4131,53600.125
...,...,...,...,...,...,...
113602,2,Marseille 8eme arrondissement (secteur 4),2026,3.0,0.3820,53600.125
113603,2,Marseille 10eme arrondissement (secteur 5),2026,3.0,0.4409,53600.125
113604,2,Marseille 11eme arrondissement (secteur 6),2026,3.0,0.4125,53600.125
113605,2,Marseille 13eme arrondissement (secteur 7),2026,3.0,0.5076,53600.125
113606,2,Marseille 15eme arrondissement (secteur 8),2026,3.0,0.5772,53600.125

In [19]:
data.loc[
    data["codecommune2026"].isin(lyon_codes),
    ["tour", "nomcommune", "year", "nb_list", "pabs", pop_col],
]

,tour,nomcommune,year,nb_list,pabs,agesexcommunes/pop2014
33831,1,Lyon 1er arrondissement (secteur 1),2014,7.0,0.4208,56211.555556
33832,1,Lyon 2eme arrondissement (secteur 2),2014,6.0,0.3948,56211.555556
33833,1,Lyon 3eme arrondissement (secteur 3),2014,6.0,0.4315,56211.555556
33834,1,Lyon 4eme arrondissement (secteur 4),2014,8.0,0.4032,56211.555556
33836,1,Lyon 6eme arrondissement (secteur 6),2014,6.0,0.4126,56211.555556
33837,1,Lyon 7eme arrondissement (secteur 7),2014,7.0,0.4453,56211.555556
33838,1,Lyon 8eme arrondissement (secteur 8),2014,7.0,0.4991,56211.555556
33839,1,Lyon 9eme arrondissement (secteur 9),2014,7.0,0.4927,56211.555556
37548,2,Lyon 1er arrondissement (secteur 1),2014,3.0,0.4210,56211.555556
37549,2,Lyon 2eme arrondissement (secteur 2),2014,3.0,0.4003,56211.555556
37550,2,Lyon 3eme arrondissement (secteur 3),2014,3.0,0.4236,56211.555556
37551,2,Lyon 4eme arrondissement (secteur 4),2014,3.0,0.4093,56211.555556
37553,2,Lyon 7eme arrondissement (secteur 7),2014,3.0,0.4436,56211.555556
37554,2,Lyon 8eme arrondissement (secteur 8),2014,3.0,0.4793,56211.555556
37555,2,Lyon 9eme arrondissement (secteur 9),2014,3.0,0.4741,56211.555556
45333,1,Lyon 1er arrondissement (secteur 1),2020,8.0,0.5394,56211.555556
45334,1,Lyon 2eme arrondissement (secteur 2),2020,7.0,0.5737,56211.555556
45335,1,Lyon 3eme arrondissement (secteur 3),2020,7.0,0.6006,56211.555556
45336,1,Lyon 4eme arrondissement (secteur 4),2020,8.0,0.5578,56211.555556
45338,1,Lyon 6eme arrondissement (secteur 6),2020,7.0,0.6036,56211.555556
45339,1,Lyon 7eme arrondissement (secteur 7),2020,8.0,0.6006,56211.555556
45340,1,Lyon 8eme arrondissement (secteur 8),2020,9.0,0.6786,56211.555556
45341,1,Lyon 9eme arrondissement (secteur 9),2020,8.0,0.6654,56211.555556
73767,2,Lyon 1er arrondissement (secteur 1),2020,1.0,0.5937,56211.555556
73768,2,Lyon 2eme arrondissement (secteur 2),2020,2.0,0.5772,56211.555556
73769,2,Lyon 3eme arrondissement (secteur 3),2020,3.0,0.6077,56211.555556
73770,2,Lyon 4eme arrondissement (secteur 4),2020,3.0,0.5587,56211.555556
73772,2,Lyon 6eme arrondissement (secteur 6),2020,3.0,0.5921,56211.555556
73773,2,Lyon 7eme arrondissement (secteur 7),2020,3.0,0.6203,56211.555556
73774,2,Lyon 8eme arrondissement (secteur 8),2020,2.0,0.7062,56211.555556
73775,2,Lyon 9eme arrondissement (secteur 9),2020,2.0,0.6834,56211.555556
112112,1,Lyon 1er arrondissement (secteur 1),2026,6.0,0.3082,56211.555556
112113,1,Lyon 2eme arrondissement (secteur 2),2026,5.0,0.3100,56211.555556
112114,1,Lyon 3eme arrondissement (secteur 3),2026,6.0,0.3290,56211.555556
112115,1,Lyon 4eme arrondissement (secteur 4),2026,6.0,0.3078,56211.555556
112117,1,Lyon 6eme arrondissement (secteur 6),2026,5.0,0.2940,56211.555556
112118,1,Lyon 7eme arrondissement (secteur 7),2026,6.0,0.3436,56211.555556
112119,1,Lyon 8eme arrondissement (secteur 8),2026,6.0,0.4372,56211.555556
112120,1,Lyon 9eme arrondissement (secteur 9),2026,6.0,0.4211,56211.555556
113607,2,Lyon 1er arrondissement (secteur 1),2026,2.0,0.3018,56211.555556
113608,2,Lyon 2eme arrondissement (secteur 2),2026,2.0,0.2965,56211.555556
113609,2,Lyon 3eme arrondissement (secteur 3),2026,2.0,0.3131,56211.555556
113610,2,Lyon 4eme arrondissement (secteur 4),2026,2.0,0.2954,56211.555556
113611,2,Lyon 6eme arrondissement (secteur 6),2026,2.0,0.3348,56211.555556
113612,2,Lyon 7eme arrondissement (secteur 7),2026,3.0,0.4257,56211.555556
113613,2,Lyon 8eme arrondissement (secteur 8),2026,3.0,0.4119,56211.555556

In [20]:
data.loc[
    data["codecommune2026"] == "77393", ["tour", "year", "nb_list", "pabs", pop_col]
]

        tour  year  nb_list    pabs  agesexcommunes/pop2014
34809      1  2014      3.0  0.3180                  2823.0
46344      1  2020      1.0  0.7461                  2823.0
107623     1  2026      3.0  0.3993                  2823.0
113281     2  2026      2.0  0.3973                  2823.0

In [21]:
vote_cols = [col for col in data.columns if "vote" in col.lower()]
print(vote_cols)

['vote_LCOM', 'pvote_LEXG', 'pvote_LUG', 'pvote_LSOC', 'vote_LUG', 'vote_LDVD', 'vote_LSOC', 'vote_LEXG', 'vote_LVEC', 'vote_LPG', 'pvote_LUD', 'pvote_LVEC', 'pvote_LUMP', 'vote_LDVG', 'pvote_LMDM', 'pvote_LEXD', 'pvote_LFN', 'vote_LEXD', 'pvote_LFG', 'vote_LUDI', 'pvote_LUC', 'vote_LUC', 'vote_LUMP', 'vote_LDIV', 'vote_LMDM', 'pvote_LUDI', 'vote_LFN', 'pvote_LPG', 'pvote_LDVG', 'pvote_LDIV', 'vote_LFG', 'pvote_LDVD', 'vote_LUD', 'pvote_LCOM', 'vote_AUTRES', 'pvote_AUTRES', 'voteG', 'pvoteG', 'voteD', 'pvoteD', 'voteCD', 'pvoteCD', 'voteCG', 'pvoteCG', 'voteC', 'pvoteC', 'voteGCG', 'voteDCD', 'voteTG', 'voteTD', 'pvoteGCG', 'pvoteDCD', 'pvoteTG', 'pvoteTD', 'vote_LRN', 'vote_LECO', 'pvote_LLR', 'pvote_LREM', 'pvote_LFI', 'pvote_LDVC', 'vote_LFI', 'vote_LLR', 'pvote_LECO', 'pvote_LRN', 'vote_LDVC', 'vote_LREM', 'pvote_LUDR', 'vote_LREN', 'vote_LREC', 'pvote_LDSV', 'vote_LUXD', 'pvote_LREN', 'pvote_LUXD', 'pvote_LREC', 'vote_LHOR', 'pvote_LHOR', 'vote_LUDR', 'vote_LDSV']

In [22]:
data[vote_cols] = data[vote_cols].fillna(0.0)

In [23]:
data.isna().astype(int).sum().to_csv("missing.csv")

In [24]:
data = data.fillna(data.mean(numeric_only=True))

In [25]:
data.isna().astype(int).sum().sum()

np.int64(0)

In [26]:
data.to_csv("final_data.csv")

- Taux de participation ajustée : 
    - Taux de participation sauf pour les communes avec une seule liste
    - Taux de vote pour un tendance : nombre de commune gagnées pondérés par le nombre