## Challenge

In [1]:
import sys
import os
import numpy as np
import pandas as pd
import s3fs
import matplotlib.pyplot as plt
import seaborn as sns
from collections import defaultdict
from dotenv import load_dotenv
project_root = '/home/onyxia/work/electera'
sys.path.insert(0, project_root)
from src.components.data_processing.data_loader import DataLoader
load_dotenv()

False

In [2]:
import os
import s3fs
os.environ["AWS_ACCESS_KEY_ID"] = 'XXXA4621E5RGRXZTKPF2'
os.environ["AWS_SECRET_ACCESS_KEY"] = '89rKPtUp0zK9KgK7KYiP0gMFSGewb3aCIL7p98Tt'
os.environ["AWS_SESSION_TOKEN"] = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJYWFhBNDYyMUU1UkdSWFpUS1BGMiIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzczNDAwMjgzLCJhenAiOiJvbnl4aWEiLCJjbmYiOnsiamt0IjoidEJITk9sZEdBYXFEdVJpZEgtVFUyT1lqa0RUN3o2LVdKclpES3gwVHA5USJ9LCJlbWFpbCI6ImFydGh1ci5tYW5jZWF1QHN0dWRlbnQtY3MuZnIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzc1MjA3NjE5LCJmYW1pbHlfbmFtZSI6Ik1hbmNlYXUiLCJnaXZlbl9uYW1lIjoiQXJ0aHVyIiwiZ3JvdXBzIjpbIlVTRVJfT05ZWElBIl0sImlhdCI6MTc3NDYwMjgxOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxhYi5zc3BjbG91ZC5mci9hdXRoL3JlYWxtcy9zc3BjbG91ZCIsImp0aSI6Im9ucnRydDpjOTNjNzJhYS1kZGYyLWViZmQtZWNhNi00Y2M4ZDIzMjM1NDYiLCJsb2NhbGUiOiJlbiIsIm5hbWUiOiJBcnRodXIgTWFuY2VhdSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhcnRodXJtYW5jZWF1IiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiJkYjViMDU0NC02NjA4LTU5NGItOGE0ZC1hMjkzMDZhNDRlZGEiLCJzdWIiOiJiYzc3Yjk3YS1lN2VkLTQ4ZWMtYmQ4Zi1lNzBjYjZhMTYyZGIiLCJ0eXAiOiJEUG9QIn0.TKYuZ6s1hiI0MH3GCWK5D4ZPndF_D4arI0UjNvJHVO4zLB2v_7XrCuq7Sx0O_pcPmPq4FjZX_Wdf8EOR8clgfQ'
os.environ["AWS_DEFAULT_REGION"] = 'us-east-1'
fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])

In [3]:
election_2014_t1 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm.parquet')
election_2014_t1['codecommune'] = election_2014_t1['codecommune'].replace({'01N01': '01283', '01N02': '01283'})
election_2014_t2 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm_t2.parquet')

election_2020_t1 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm.parquet')
election_2020_t2 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm_t2.parquet')

election_2026_t1 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm.parquet')
election_2026_t2 = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm_t2.parquet')

2026-03-28 19:18:57.460 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm.parquet...
2026-03-28 19:18:58.264 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (36350, 63)
2026-03-28 19:18:58.316 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2014/muni2014_csv/muni2014comm_t2.parquet...
2026-03-28 19:18:58.576 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (1675, 63)
2026-03-28 19:18:58.610 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm.parquet...
2026-03-28 19:18:59.118 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (34757, 75)
2026-03-28 19:18:59.171 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2020/muni2020_csv/muni2020comm_t2.parquet...
2026-03-28 19:18:59.468 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (4513, 75)
2026-03-28 19:18:59.498 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm.parquet...
2026-03-28 19:18:59.875 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (34830, 75)
2026-03-28 19:18:59.939 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/raw/elections/municipales/2026/muni2026_csv/muni2026comm_t2.parquet...
2026-03-28 19:19:00.244 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (1526, 73)

In [4]:
def clean_and_filter_dep(df):
    df['codecommune'] = df['codecommune'].astype(str).str.zfill(5)
    df['dep_num'] = df['dep'].replace({'A': 20.0, 'B': 20.0}, regex=True).astype(float)
    print("Before filter:", len(df))
    df = df[(df['dep_num'] <= 95.0) & (df['dep_num'] >= 1.0)]
    print("After filter:", len(df))
    return df

# Example usage for all datasets:
election_2014_t1 = clean_and_filter_dep(election_2014_t1)
election_2014_t2 = clean_and_filter_dep(election_2014_t2)
election_2020_t1 = clean_and_filter_dep(election_2020_t1)
election_2020_t2 = clean_and_filter_dep(election_2020_t2)
election_2026_t1 = clean_and_filter_dep(election_2026_t1)
election_2026_t2 = clean_and_filter_dep(election_2026_t2)

Before filter: 36350
After filter: 36350
Before filter: 1675
After filter: 1675
Before filter: 34757
After filter: 34757
Before filter: 4513
After filter: 4513
Before filter: 34830
After filter: 34666
Before filter: 1526
After filter: 1445

In [5]:
# Add year, tour, type columns
election_2014_t1['year'] = 2014
election_2014_t1['tour'] = 1
election_2014_t1['type'] = "muni"

election_2014_t2['year'] = 2014
election_2014_t2['tour'] = 2
election_2014_t2['type'] = "muni"

election_2020_t1['year'] = 2020
election_2020_t1['tour'] = 1
election_2020_t1['type'] = "muni"

election_2020_t2['year'] = 2020
election_2020_t2['tour'] = 2
election_2020_t2['type'] = "muni"

election_2026_t1['year'] = 2026
election_2026_t1['tour'] = 1
election_2026_t1['type'] = "muni"

election_2026_t2['year'] = 2026
election_2026_t2['tour'] = 2
election_2026_t2['type'] = "muni"

# Concatenate all datasets
elections = pd.concat([
    election_2014_t1, election_2014_t2,
    election_2020_t1, election_2020_t2,
    election_2026_t1, election_2026_t2
], axis=0)

In [6]:
socio_eco = DataLoader().load_dataset('s3://arthurmanceau/election_modeling_uhcp/data/derived/cache/dfc_cached.parquet')

2026-03-28 19:19:00.733 | DEBUG    | src.components.data_processing.data_loader:_read_parquet:62 - Loading dataset from s3://arthurmanceau/election_modeling_uhcp/data/derived/cache/dfc_cached.parquet...

2026-03-28 19:19:41.980 | DEBUG    | src.components.data_processing.data_loader:load_dataset:205 - Dataset loaded: (38145, 31557)

In [7]:
cols_2019 = [col for col in socio_eco.columns if '2019' in col]
cols_2019

['agesexcommunes/popf0142019',
 'agesexcommunes/popf15392019',
 'agesexcommunes/popf40592019',
 'agesexcommunes/popf60p2019',
 'agesexcommunes/poph0142019',
 'agesexcommunes/poph15392019',
 'agesexcommunes/poph40592019',
 'agesexcommunes/poph60p2019',
 'agesexcommunes/agef2019',
 'agesexcommunes/ageh2019',
 'agesexcommunes/popf2019',
 'agesexcommunes/poph2019',
 'agesexcommunes/propf2019',
 'agesexcommunes/age2019',
 'agesexcommunes/pop2019',
 'agesexcommunes/propf0142019',
 'agesexcommunes/propf15392019',
 'agesexcommunes/propf40592019',
 'agesexcommunes/propf60p2019',
 'agesexcommunes/prop0142019',
 'agesexcommunes/prop15392019',
 'agesexcommunes/prop40592019',
 'agesexcommunes/prop60p2019',
 'agesexcommunes/perpropf2019',
 'agesexcommunes/perage2019',
 'agesexcommunes/perprop0142019',
 'agesexcommunes/perprop60p2019',
 'agesexdepartements/popf2019',
 'agesexdepartements/poph2019',
 'agesexdepartements/popf0142019',
 'agesexdepartements/popf15392019',
 'agesexdepartements/popf40592019',
 'agesexdepartements/popf60p2019',
 'agesexdepartements/poph0142019',
 'agesexdepartements/poph15392019',
 'agesexdepartements/poph40592019',
 'agesexdepartements/poph60p2019',
 'agesexdepartements/agef2019',
 'agesexdepartements/ageh2019',
 'agesexdepartements/age2019',
 'agesexdepartements/pop2019',
 'agesexdepartements/propf2019',
 'agesexdepartements/propf0142019',
 'agesexdepartements/propf15392019',
 'agesexdepartements/propf40592019',
 'agesexdepartements/propf60p2019',
 'agesexdepartements/prop0142019',
 'agesexdepartements/prop15392019',
 'agesexdepartements/prop40592019',
 'agesexdepartements/prop60p2019',
 'cspcommunes/agri2019',
 'cspcommunes/indp2019',
 'cspcommunes/cadr2019',
 'cspcommunes/pint2019',
 'cspcommunes/empl2019',
 'cspcommunes/ouvr2019',
 'cspcommunes/chom2019',
 'cspcommunes/aind2019',
 'cspcommunes/aica2019',
 'cspcommunes/ouem2019',
 'cspcommunes/capi2019',
 'cspcommunes/pact2019',
 'cspcommunes/pagri2019',
 'cspcommunes/pindp2019',
 'cspcommunes/pcadr2019',
 'cspcommunes/ppint2019',
 'cspcommunes/pempl2019',
 'cspcommunes/pouvr2019',
 'cspcommunes/paind2019',
 'cspcommunes/paica2019',
 'cspcommunes/pouem2019',
 'cspcommunes/pcapi2019',
 'cspcommunes/pchom2019',
 'cspcommunes/peragri2019',
 'cspcommunes/perindp2019',
 'cspcommunes/percadr2019',
 'cspcommunes/perpint2019',
 'cspcommunes/perempl2019',
 'cspcommunes/perouvr2019',
 'cspcommunes/perchom2019',
 'cspcommunes/peraind2019',
 'cspcommunes/peraica2019',
 'cspcommunes/perouem2019',
 'cspcommunes/percapi2019',
 'rsacommunes/nrsa2019',
 'rsacommunes/nfoyerrsa2019',
 'rsacommunes/prsa2019',
 'rsacommunes/perrsa2019',
 'rsacommunes/pop2019',
 'basesfiscalescommunes/baseimpotslocauxratio2019',
 'basesfiscalescommunes/recetteimpotslocauxratio2019',
 'basesfiscalescommunes/tauximpotslocauxratio2019',
 'basesfiscalescommunes/baseimpotslocauxtot2019',
 'basesfiscalescommunes/recetteimpotslocauxtot2019',
 'basesfiscalescommunes/tauximpotslocaux2019',
 'basesfiscalescommunes/recettetot2019',
 'basesfiscalescommunes/baseimpotslocaux2019',
 'basesfiscalescommunes/recetteimpotslocaux2019',
 'basesfiscalescommunes/recettefoncieretot2019',
 'basesfiscalescommunes/recettehabitationtot2019',
 'basesfiscalescommunes/recettefonciere2019',
 'basesfiscalescommunes/recettehabitation2019',
 'basesfiscalescommunes/recettefonciereratio2019',
 'basesfiscalescommunes/recettehabitationratio2019',
 'basesfiscalescommunes/basehabitationratio2019',
 'basesfiscalescommunes/basefonciereratio2019',
 'basesfiscalescommunes/tauxhabitationratio2019',
 'basesfiscalescommunes/tauxfoncierratio2019',
 'basesfiscalescommunes/basehabitationtot2019',
 'basesfiscalescommunes/basefoncieretot2019',
 'basesfiscalescommunes/tauxhabitation2019',
 'basesfiscalescommunes/tauxfoncier2019',
 'basesfiscalescommunes/basehabitation2019',
 'basesfiscalescommunes/basefonciere2019',
 'basesfiscalescommunes/pop2019',
 'basesfiscalescommunes/recetteratio2019',
 'basesfiscalesdepartements/basehabitationratio2019',
 'basesfiscalesdepartements/basefonciereratio2019',
 'basesfiscalesdepartements/baseimpotslocauxratio2019',
 'basesfiscalesdepartements/basehabitation2019',
 'basesfiscalesdepartements/basefonciere2019',
 'basesfiscalesdepartements/baseimpotslocaux2019',
 'basesfiscalesdepartements/pop2019',
 'basesfiscalesdepartements/recettehabitationratio2019',
 'basesfiscalesdepartements/recettefonciereratio2019',
 'basesfiscalesdepartements/recettehabitation2019',
 'basesfiscalesdepartements/recettefonciere2019',
 'basesfiscalesdepartements/tauxhabitationratio2019',
 'basesfiscalesdepartements/tauxfonciereratio2019',
 'basesfiscalesdepartements/recetteimpotslocauxratio2019',
 'basesfiscalesdepartements/tauximpotslocauxratio2019',
 'basesfiscalesdepartements/recetteimpotslocaux2019',
 'basesfiscalesdepartements/recetteratio2019',
 'basesfiscalesdepartements/recette2019',
 'capitalimmobiliercommunes/capitalratio2019',
 'capitalimmobiliercommunes/capitalratioagglo2019',
 'capitalimmobiliercommunes/capitalimmo2019',
 'capitalimmobiliercommunes/capitalimmoagglo2019',
 'capitalimmobiliercommunes/prixbien2019',
 'capitalimmobiliercommunes/surfaceterrain2019',
 'capitalimmobiliercommunes/pop2019',
 'capitalimmobiliercommunes/percapagglo2019',
 'capitalimmobiliercommunes/surface2019',
 'capitalimmobiliercommunes/propappartementdep2019',
 'capitalimmobiliercommunes/propappartement2019',
 'capitalimmobiliercommunes/prixm22019',
 'capitalimmobiliercommunes/prixm2ratio2019',
 'capitalimmobiliercommunes/percap2019',
 'capitalimmobilierdepartements/capitalratio2019',
 'capitalimmobilierdepartements/capitalimmo2019',
 'capitalimmobilierdepartements/prixbien2019',
 'capitalimmobilierdepartements/prixm2ratio2019',
 'capitalimmobilierdepartements/prixm22019',
 'capitalimmobilierdepartements/surface2019',
 'capitalimmobilierdepartements/surfaceterrain2019',
 'capitalimmobilierdepartements/propappartement2019',
 'capitalimmobilierdepartements/pop2019',
 'diplomescommunes/nodiph2019',
 'diplomescommunes/bach2019',
 'diplomescommunes/suph2019',
 'diplomescommunes/nodipf2019',
 'diplomescommunes/bacf2019',
 'diplomescommunes/supf2019',
 'diplomescommunes/nodip2019',
 'diplomescommunes/bac2019',
 'diplomescommunes/sup2019',
 'diplomescommunes/pbac2019',
 'diplomescommunes/perbac2019',
 'diplomescommunes/psup2019',
 'diplomescommunes/persup2019',
 'diplomesdepartements/nodiph2019',
 'diplomesdepartements/nodipf2019',
 'diplomesdepartements/nodip2019',
 'diplomesdepartements/bach2019',
 'diplomesdepartements/bacf2019',
 'diplomesdepartements/bac2019',
 'diplomesdepartements/suph2019',
 'diplomesdepartements/supf2019',
 'diplomesdepartements/sup2019',
 'diplomesdepartements/pbac2019',
 'diplomesdepartements/psup2019',
 'etrangerscommunes/etranger2019',
 'etrangerscommunes/francais2019',
 'etrangerscommunes/peretranger2019',
 'etrangerscommunes/petranger2019',
 'naticommunes/petranger2019',
 'naticommunes/peretr2019',
 'naticommunes/francais2019',
 'naticommunes/etranger2019',
 'naticommunes/pop2019',
 'natidepartements/etranger2019',
 'natidepartements/francais2019',
 'natidepartements/petranger2019',
 'natidepartements/pop2019',
 'proprietairescommunes/ppropri2019',
 'proprietairescommunes/nlogement2019',
 'proprietairescommunes/npropri2019',
 'proprietairescommunes/perpropri2019',
 'pibcommunes/perpibratio2019',
 'pibcommunes/pibratio2019',
 'pibcommunes/pibtot2019',
 'pibcommunes/pop2019',
 'pibdepartements/pibhab2019',
 'pibdepartements/pib2019',
 'pibdepartements/pop2019',
 'revcommunes/revratio2019',
 'revcommunes/revtot2019',
 'revcommunes/revtotagglo2019',
 'revcommunes/revratioagglo2019',
 'revcommunes/perrevagglo2019',
 'revcommunes/revratioadu2019',
 'revcommunes/revratiofoy2019',
 'revcommunes/pop2019',
 'revcommunes/nadult2019',
 'revcommunes/nfoyer2019',
 'revcommunes/revmoy2019',
 'revcommunes/revmoyadu2019',
 'revcommunes/revmoyfoy2019',
 'revcommunes/perrevfoy2019',
 'revcommunes/perrevadu2019',
 'revcommunes/perrev2019',
 'revdepartements/revratio2019',
 'revdepartements/revratioadu2019',
 'revdepartements/revratiofoy2019',
 'revdepartements/revtot2019',
 'revdepartements/pop2019',
 'revdepartements/nadult2019',
 'revdepartements/nfoyer2019',
 'revdepartements/revmoyfoy2019',
 'revdepartements/revmoyadu2019',
 'revdepartements/revmoy2019',
 'revimpdepartements/pop2019',
 'revimpdepartements/popcom2u2019',
 'revimpdepartements/popcom5u2019',
 'revimpdepartements/popcom10u2019',
 'revimpdepartements/popcoma2019',
 'popcommunes/popagglo2019',
 'popcommunes/pop2019',
 'popcommunes/percommu2019',
 'popcommunes/peragglo2019',
 'popcommuneselecteurs/electeurs2019',
 'popcommunesvbbm/vbbm2019',
 'popcommunesvbbm/vbbmpauvresriches2019',
 'popcommunesvbbm/vbbmpauvresrichescap2019',
 'popdepartements/pop2019',
 'popdepartements/popcom2u2019',
 'popdepartements/popcom5u2019',
 'popdepartements/popcom10u2019',
 'popdepartements/popcoma2019']

In [8]:
features = [
    'agesexcommunes/pop2018',
    'agesexcommunes/age2018',
    'cspcommunes/pagri2018',
    'cspcommunes/pindp2018',
    'cspcommunes/pcadr2018',
    'cspcommunes/ppint2018',
    'cspcommunes/pempl2018',
    'cspcommunes/pouvr2018',
    'cspcommunes/paind2018',
    'cspcommunes/paica2018',
    'cspcommunes/pouem2018',
    'cspcommunes/pcapi2018',
    'cspcommunes/pchom2018',
    'basesfiscalescommunes/tauxfoncier2018',
    'capitalimmobiliercommunes/prixm2ratio2018',
    'diplomesdepartements/psup2018',
    'proprietairescommunes/ppropri2018',
    'popcommunesvbbm/vbbm2018',
    'popcommunesvbbm/vbbmpauvresriches2018',
    'pibdepartements/pibhab2018',
    'etrangerscommunes/petranger2018',
    'revcommunes/revratio2018', 
    'codecommune']

In [9]:
socio_eco_filtered = socio_eco[features]
# Drop rows where 'codecommune' is not 5 digits
socio_eco_filtered = socio_eco_filtered[socio_eco_filtered['codecommune'].astype(str).str.len() == 5]

In [10]:
data = elections.merge(socio_eco_filtered, on='codecommune', how='left', validate='m:1')

In [11]:
marseille_codes = [
    '13201', '13202', '13205', '13207', '13209', '13211', '13213', '13215'
]
# For these, set their values to those of 13055 (Marseille)
if 'codecommune' in data.columns:
    mask_marseille = data['codecommune'].isin(marseille_codes)
    marseille_row = data[data['codecommune'] == '13055']
    if not marseille_row.empty:
        for code in marseille_codes:
            data.loc[data['codecommune'] == code, :] = marseille_row.values[0]

# List of Lyon arrondissements codes to update
lyon_codes = [
    '69381', '69382', '69383', '69384', '69385', '69386', '69387', '69388', '69389'
]


lyon_row = socio_eco_filtered[socio_eco_filtered['codecommune'] == '69123']
if not lyon_row.empty:
        for code in lyon_codes:
            idx = data[data['codecommune'] == code].index
            if not idx.empty:
                # Only update columns that exist in both dataframes
                common_cols = list(set(data.columns) & set(socio_eco_filtered.columns))
                for col in common_cols:
                    data.loc[idx, col] = lyon_row.iloc[0][col]

In [12]:
data

,% Nuls/inscrits,% Abstentions,nomcommune,% Blancs/inscrits,codecommune,% Nuls/votants,% Votants,votants,exprimes,nomdep,...,cspcommunes/pchom2018,basesfiscalescommunes/tauxfoncier2018,capitalimmobiliercommunes/prixm2ratio2018,diplomesdepartements/psup2018,proprietairescommunes/ppropri2018,popcommunesvbbm/vbbm2018,popcommunesvbbm/vbbmpauvresriches2018,pibdepartements/pibhab2018,etrangerscommunes/petranger2018,revcommunes/revratio2018
0,2.33,40.73,L'Abergement-ClÈmenciat,0.00,01001,3.94,59.26,355,341,AIN,...,0.084967,0.141213,0.719930,0.294438,0.822165,1.0,2.0,0.731279,0.008997,1.096172
1,0.44,16.37,L'Abergement-de-Varey,0.00,01002,0.52,83.62,189,188,AIN,...,0.074468,0.123875,0.472579,0.294438,0.810345,1.0,2.0,0.731279,0.008000,1.047167
2,2.80,35.51,AmblÈon,0.00,01006,4.34,64.48,69,66,AIN,...,0.000000,0.154701,0.582246,0.294438,0.661972,1.0,2.0,0.731279,0.062500,1.018453
3,2.08,39.30,Ambutrix,0.00,01008,3.43,60.69,349,337,AIN,...,0.028125,0.163896,0.684019,0.294438,0.718182,2.0,4.0,0.731279,0.023841,1.068166
4,1.15,30.88,Andert-et-Condon,0.00,01009,1.67,69.11,179,176,AIN,...,0.029851,0.066225,0.560522,0.294438,0.817647,1.0,2.0,0.731279,0.030395,1.408379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113401,0.44,46.73,Soisy-sous-Montmorency,0.53,95598,0.84,53.27,6467,6349,Val-d'Oise,...,0.075495,0.143028,1.316012,0.336019,0.590133,3.0,6.0,0.865744,0.117615,1.204876
113402,0.59,43.98,Le Thillay,0.55,95612,1.06,56.02,1419,1390,Val-d'Oise,...,0.072239,0.183042,1.014789,0.336019,0.783660,3.0,5.0,0.865744,0.139636,0.846481
113403,0.41,20.00,Vallangoujard,0.20,95627,0.51,80.00,392,389,Val-d'Oise,...,0.000000,0.109211,0.963784,0.336019,0.887931,1.0,2.0,0.865744,0.032841,1.625421
113404,0.21,41.05,Vémars,0.36,95641,0.35,58.95,1146,1135,Val-d'Oise,...,0.058708,0.195378,1.050061,0.336019,0.712029,2.0,4.0,0.865744,0.063847,1.190314
113405,0.57,50.27,Villiers-le-Bel,0.54,95680,1.15,49.73,6808,6656,Val-d'Oise,...,0.125117,0.205694,0.873483,0.336019,0.375284,3.0,5.0,0.865744,0.251037,0.619307

In [13]:
data.to_csv('final_data.csv')

In [14]:
data.loc[data['codecommune']=='77393', ['tour', 'year', 'nb_list', 'pabs']]

        tour  year  nb_list    pabs
34776      1  2014      3.0  0.3180
46269      1  2020      1.0  0.7461
107492     1  2026      3.0  0.3993
113098     2  2026      2.0  0.3973