In [1]:
from src.components.data_processing.data_loader import DataLoader, DataUtils
from loguru import logger
import re
import polars.selectors as cs

In [2]:
import os
import s3fs
import polars as pl
os.environ["AWS_ACCESS_KEY_ID"] = 'H9OECGSDIR9AQ9S65ZGV'
os.environ["AWS_SECRET_ACCESS_KEY"] = 'jl6EjjznVonoxzL3eGDhpGMmz1gbkrzN+TXzpnL2'
os.environ["AWS_SESSION_TOKEN"] = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJIOU9FQ0dTRElSOUFROVM2NVpHViIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzc3MDM1NjAyLCJhenAiOiJvbnl4aWEiLCJjbmYiOnsiamt0IjoiSE51MEVHcHVuQ3k1emRjcmhaWExGUWF0TjRPSVNFbWZtZnk1a3k3MlBINCJ9LCJlbWFpbCI6ImFydGh1ci5tYW5jZWF1QHN0dWRlbnQtY3MuZnIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzc3OTA1ODM4LCJmYW1pbHlfbmFtZSI6Ik1hbmNlYXUiLCJnaXZlbl9uYW1lIjoiQXJ0aHVyIiwiZ3JvdXBzIjpbIlVTRVJfT05ZWElBIl0sImlhdCI6MTc3NzMwMTAzOCwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxhYi5zc3BjbG91ZC5mci9hdXRoL3JlYWxtcy9zc3BjbG91ZCIsImp0aSI6Im9ucnRydDo5YWI3N2ZlNC03NDRjLTU0MjAtZjc5Ni0yZDVhYzQ0ZmRiZTciLCJsb2NhbGUiOiJlbiIsIm5hbWUiOiJBcnRodXIgTWFuY2VhdSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhcnRodXJtYW5jZWF1IiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiI4OTYwMGU5ZC1jMTg2LTYwY2MtN2Q5Mi05Njg1OTIxZDY2MTIiLCJzdWIiOiJiYzc3Yjk3YS1lN2VkLTQ4ZWMtYmQ4Zi1lNzBjYjZhMTYyZGIiLCJ0eXAiOiJEUG9QIn0.Km_a0cUNOqv8YGCUeMQYknjaxvyV2tf_ruDU5m4QEsDINjFulZThi2suv6OpCutYbIamkHmZyijXuqsZl_X-dQ'
os.environ["AWS_DEFAULT_REGION"] = 'us-east-1'
fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])
storage_options = {
    "aws_access_key_id": os.environ["AWS_ACCESS_KEY_ID"] ,
    "aws_secret_access_key": os.environ["AWS_SECRET_ACCESS_KEY"],
    "aws_region": os.environ["AWS_DEFAULT_REGION"] ,
}

In [3]:
communes = pl.scan_csv('s3://arthurmanceau/election_modeling_uhcp/data/raw/insee_geo/2026/communes_2026.csv', storage_options=storage_options, infer_schema_length=40000).collect()

In [4]:
communes = communes.with_columns(
    DEP_NUM = pl.col('DEP').replace({'2A': 20, '2B': 20}).cast(pl.Int64),
    codecommune = pl.col("COM").cast(pl.String).str.zfill(5)
)

A priori on garde toutes les communes selon toutes les modalités on fera le tri après.

In [5]:
communes

shape: (37_496, 14)
┌─────────┬───────┬─────┬─────┬───┬───────┬───────────┬─────────┬─────────────┐
│ TYPECOM ┆ COM   ┆ REG ┆ DEP ┆ … ┆ CAN   ┆ COMPARENT ┆ DEP_NUM ┆ codecommune │
│ ---     ┆ ---   ┆ --- ┆ --- ┆   ┆ ---   ┆ ---       ┆ ---     ┆ ---         │
│ str     ┆ str   ┆ i64 ┆ str ┆   ┆ str   ┆ i64       ┆ i64     ┆ str         │
╞═════════╪═══════╪═════╪═════╪═══╪═══════╪═══════════╪═════════╪═════════════╡
│ COM     ┆ 1001  ┆ 84  ┆ 1   ┆ … ┆ 108   ┆ null      ┆ 1       ┆ 01001       │
│ COM     ┆ 1002  ┆ 84  ┆ 1   ┆ … ┆ 101   ┆ null      ┆ 1       ┆ 01002       │
│ COM     ┆ 1004  ┆ 84  ┆ 1   ┆ … ┆ 101   ┆ null      ┆ 1       ┆ 01004       │
│ COM     ┆ 1005  ┆ 84  ┆ 1   ┆ … ┆ 122   ┆ null      ┆ 1       ┆ 01005       │
│ COM     ┆ 1006  ┆ 84  ┆ 1   ┆ … ┆ 104   ┆ null      ┆ 1       ┆ 01006       │
│ …       ┆ …     ┆ …   ┆ …   ┆ … ┆ …     ┆ …         ┆ …       ┆ …           │
│ COM     ┆ 97613 ┆ 6   ┆ 976 ┆ … ┆ 97613 ┆ null      ┆ 976     ┆ 97613       │
│ COM     ┆ 97614 ┆ 6   ┆ 976 ┆ … ┆ 97610 ┆ null      ┆ 976     ┆ 97614       │
│ COM     ┆ 97615 ┆ 6   ┆ 976 ┆ … ┆ 97611 ┆ null      ┆ 976     ┆ 97615       │
│ COM     ┆ 97616 ┆ 6   ┆ 976 ┆ … ┆ 97612 ┆ null      ┆ 976     ┆ 97616       │
│ COM     ┆ 97617 ┆ 6   ┆ 976 ┆ … ┆ 97613 ┆ null      ┆ 976     ┆ 97617       │
└─────────┴───────┴─────┴─────┴───┴───────┴───────────┴─────────┴─────────────┘

In [3]:
data_path = "s3://arthurmanceau/election_modeling_uhcp/data/"
elections_to_exclude = []
vote_variables = [
        "ppar",
        "pvoteD",
        "pvoteG",
        "pvoteCG",
        "pvoteCD",
        "pvoteC",
        "pvoteTD",
        "pvoteTG",
        "pvoteGCG",
        "pvoteDCD"
    ] # Extract all a priori

In [27]:
def interpret_election_path(relative_path):
    path_element = relative_path.split(os.sep)[-3:]  # ['legislative', '1848', 'leg1848_csv']
    election_type = path_element[0]  # 'legislative'
    year = path_element[1]  # '1848'
    election_code = path_element[2].split('_')[0] # leg1848
    return election_type, year, election_code

def load_electoral_data():
    """Function that loads all electoral dataset"""
    folder_path = os.path.join(data_path + "raw/", "elections/")
    election_datasets = {}
    xs = (
        DataUtils._create_fs()
        if DataUtils._detect_s3(data_path)
        else os
    )
    for root, dirs, files in xs.walk(folder_path):
        for dir in dirs:
            for root, _, files in xs.walk(os.path.join(folder_path, dir)):
                for file in files:
                    if (
                            file.endswith(".parquet")
                            and (not file.startswith("."))
                            and file not in elections_to_exclude
                    ):
                        election_type, year, election_code = interpret_election_path(os.path.relpath(root, folder_path))
                        logger.debug(f"Processing election : {(election_type, year)}")

                        file_path = DataUtils.path_helper(
                            folder_path, os.path.join(root, file)
                        )
                        election_datasets[election_code] = pl.scan_parquet(file_path).collect()

    return election_datasets

helper_cols = set({'dep','nomdep','codecommune','nomcommune', 'plm'})
def load_socio_economic_data():
    folder_path = os.path.join(data_path, "raw/")
    socio_economic_dataset = {}
    xs = (
        DataUtils._create_fs()
        if DataUtils._detect_s3(data_path)
        else os
    )
    for root, dirs, files in xs.walk(folder_path):
        for dir in dirs:
            if dir != 'elections':
                for root, _, files in xs.walk(os.path.join(folder_path, dir)):
                    for file in files:
                        if (
                                file.endswith(".parquet")
                                and (not file.startswith("."))
                        ):
                            if 'communes' in file:
                                key = 'codecommune'
                            else:
                                key = 'dep'
                            print(key)
                            file_path = DataUtils.path_helper(
                                folder_path, os.path.join(root, file)
                            )
                            data_code = file_path.split('/')[-1].split('.')[0]
                            logger.debug(f"Processing file : {data_code}")
                            
                            df = pl.scan_parquet(file_path).collect()

                            # Identify features
                            all_feature_years = df.select(cs.matches(r".*\d{4}$")).columns

                            # Single unpivot for all features
                            df_long = df.unpivot(
                                on=all_feature_years,
                                index=list(set(df.columns).intersection(helper_cols)),
                                variable_name="variable",
                                value_name="raw",
                            ).with_columns(
                                pl.col("raw").cast(pl.Float64, strict=True),
                                year=pl.col("variable").str.tail(4).cast(pl.Int32),
                                feature_name=pl.col("variable").str.head(-4),
                            ).sort(
                                [key, "feature_name", "year"]
                            ).with_columns(
                                lag=pl.col("raw").shift(1).over(key, "feature_name"),
                                rank=pl.col("raw").rank("dense").over(key, "feature_name"),
                                delta=pl.col("raw").diff(1).over(key, "feature_name"),
                                pct_change=pl.col("raw").pct_change(1).over(key, "feature_name"),
                            )
                            socio_economic_dataset[data_code] = df_long
                            
    return socio_economic_dataset

In [113]:
election_datasets = load_electoral_data()

2026-04-27 15:45:58.649 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1848')
2026-04-27 15:45:58.839 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1849')
2026-04-27 15:45:59.050 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1850')
2026-04-27 15:45:59.271 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1851')
2026-04-27 15:45:59.463 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1871')
2026-04-27 15:45:59.627 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1872')
2026-04-27 15:45:59.799 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1874')
2026-04-27 15:45:59.961 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1876')
2026-04-27 15:46:00.164 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1877')
2026-04-27 15:46:00.358 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1881')
2026-04-27 15:46:00.534 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1882')
2026-04-27 15:46:00.742 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1885')
2026-04-27 15:46:00.959 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1886')
2026-04-27 15:46:01.173 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1889')
2026-04-27 15:46:01.376 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1890')
2026-04-27 15:46:01.561 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1893')
2026-04-27 15:46:01.767 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1894')
2026-04-27 15:46:01.962 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1898')
2026-04-27 15:46:02.142 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1899')
2026-04-27 15:46:02.323 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1906')
2026-04-27 15:46:02.529 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1907')
2026-04-27 15:46:02.722 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1910')
2026-04-27 15:46:02.937 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1911')
2026-04-27 15:46:03.129 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1914')
2026-04-27 15:46:03.325 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1915')
2026-04-27 15:46:03.545 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1919')
2026-04-27 15:46:03.755 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1924')
2026-04-27 15:46:03.970 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1928')
2026-04-27 15:46:04.151 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1932')
2026-04-27 15:46:04.357 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1936')
2026-04-27 15:46:04.553 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1945')
2026-04-27 15:46:04.768 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1946')
2026-04-27 15:46:04.968 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1947')
2026-04-27 15:46:05.147 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1951')
2026-04-27 15:46:05.383 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1956')
2026-04-27 15:46:05.574 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1958')
2026-04-27 15:46:05.765 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1962')
2026-04-27 15:46:05.960 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1967')
2026-04-27 15:46:06.159 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1968')
2026-04-27 15:46:06.366 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1973')
2026-04-27 15:46:06.554 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1978')
2026-04-27 15:46:06.772 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1981')
2026-04-27 15:46:06.987 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1986')
2026-04-27 15:46:07.175 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1988')
2026-04-27 15:46:07.366 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1993')
2026-04-27 15:46:07.578 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '1997')
2026-04-27 15:46:07.786 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '2002')
2026-04-27 15:46:07.977 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '2007')
2026-04-27 15:46:08.191 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '2012')
2026-04-27 15:46:08.420 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '2017')
2026-04-27 15:46:08.622 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '2022')
2026-04-27 15:46:08.829 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('legislative', '2024')
2026-04-27 15:46:09.015 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('municipales', '2014')
2026-04-27 15:46:09.154 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('municipales', '2014')
2026-04-27 15:46:09.277 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('municipales', '2020')
2026-04-27 15:46:09.431 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('municipales', '2020')
2026-04-27 15:46:09.567 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('municipales', '2026')
2026-04-27 15:46:09.712 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('municipales', '2026')
2026-04-27 15:46:09.851 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '1848')
2026-04-27 15:46:10.023 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '1965')
2026-04-27 15:46:10.225 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '1969')
2026-04-27 15:46:10.421 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '1974')
2026-04-27 15:46:10.609 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '1981')
2026-04-27 15:46:10.836 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '1988')
2026-04-27 15:46:11.052 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '1995')
2026-04-27 15:46:11.255 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '2002')
2026-04-27 15:46:11.461 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '2007')
2026-04-27 15:46:11.682 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '2012')
2026-04-27 15:46:11.877 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '2017')
2026-04-27 15:46:12.077 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '2022')
2026-04-27 15:46:12.292 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('presidentiel', '2027')
2026-04-27 15:46:12.481 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('referendum', '1793')
2026-04-27 15:46:12.646 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('referendum', '1795')
2026-04-27 15:46:12.793 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('referendum', '1946')
2026-04-27 15:46:12.982 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('referendum', '1992')
2026-04-27 15:46:13.120 | DEBUG    | __main__:load_electoral_data:27 - Processing election : ('referendum', '2005')

In [ ]:
socio_economic_data = load_socio_economic_data()

2026-04-27 16:38:27.785 | DEBUG    | __main__:load_socio_economic_data:63 - Processing file : agesexcommunes

codecommune

In [145]:
socio_economic_data['menagescommunes']

shape: (36_434, 9)
┌─────┬────────────┬─────────────┬──────────────────┬───┬──────┬──────────┬───────────┬────────────┐
│ dep ┆ nomdep     ┆ codecommune ┆ nomcommune       ┆ … ┆ nmen ┆ nmencomp ┆ pmencomp  ┆ permencomp │
│ --- ┆ ---        ┆ ---         ┆ ---              ┆   ┆ ---  ┆ ---      ┆ ---       ┆ ---        │
│ str ┆ str        ┆ str         ┆ str              ┆   ┆ i64  ┆ i64      ┆ f64       ┆ f64        │
╞═════╪════════════╪═════════════╪══════════════════╪═══╪══════╪══════════╪═══════════╪════════════╡
│ 01  ┆ AIN        ┆ 01001       ┆ ABERGEMENT-CLEME ┆ … ┆ 124  ┆ 3        ┆ 0.024194  ┆ 0.001428   │
│     ┆            ┆             ┆ NCIAT            ┆   ┆      ┆          ┆           ┆            │
│ 01  ┆ AIN        ┆ 01002       ┆ ABERGEMENT-DE-VA ┆ … ┆ 53   ┆ 3        ┆ 0.056604  ┆ 0.279386   │
│     ┆            ┆             ┆ REY              ┆   ┆      ┆          ┆           ┆            │
│ 01  ┆ AIN        ┆ 01004       ┆ AMBERIEU-EN-BUGE ┆ … ┆ 3200 ┆ 159      ┆ 0.049688  ┆ 0.165093   │
│     ┆            ┆             ┆ Y                ┆   ┆      ┆          ┆           ┆            │
│ 01  ┆ AIN        ┆ 01005       ┆ AMBERIEUX-EN-DOM ┆ … ┆ 243  ┆ 12       ┆ 0.049383  ┆ 0.15957    │
│     ┆            ┆             ┆ BES              ┆   ┆      ┆          ┆           ┆            │
│ 01  ┆ AIN        ┆ 01006       ┆ AMBLEON          ┆ … ┆ 29   ┆ 5        ┆ 0.1724138 ┆ 0.957667   │
│ …   ┆ …          ┆ …           ┆ …                ┆ … ┆ …    ┆ …        ┆ …         ┆ …          │
│ 95  ┆ VAL-D'OISE ┆ 95676       ┆ VILLERS-EN-ARTHI ┆ … ┆ 97   ┆ 5        ┆ 0.051546  ┆ 0.190179   │
│     ┆            ┆             ┆ ES               ┆   ┆      ┆          ┆           ┆            │
│ 95  ┆ VAL-D'OISE ┆ 95678       ┆ VILLIERS-ADAM    ┆ … ┆ 206  ┆ 15       ┆ 0.072816  ┆ 0.565188   │
│ 95  ┆ VAL-D'OISE ┆ 95680       ┆ VILLIERS-LE-BEL  ┆ … ┆ 6710 ┆ 540      ┆ 0.080477  ┆ 0.664478   │
│ 95  ┆ VAL-D'OISE ┆ 95682       ┆ VILLIERS-LE-SEC  ┆ … ┆ 57   ┆ 7        ┆ 0.122807  ┆ 0.890934   │
│ 95  ┆ VAL-D'OISE ┆ 95690       ┆ WY-DIT-JOLI-VILL ┆ … ┆ 62   ┆ 1        ┆ 0.016129  ┆ 0.000795   │
│     ┆            ┆             ┆ AGE              ┆   ┆      ┆          ┆           ┆            │
└─────┴────────────┴─────────────┴──────────────────┴───┴──────┴──────────┴───────────┴────────────┘

In [139]:
socio_economic_data['agesexcommunes']

shape: (37_985, 2_385)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ dep ┆ nomdep     ┆ codecommun ┆ nomcommune ┆ … ┆ perpropf19 ┆ perage1959 ┆ perprop01 ┆ perprop60 │
│ --- ┆ ---        ┆ e          ┆ ---        ┆   ┆ 59         ┆ ---        ┆ 41959     ┆ p1959     │
│ str ┆ str        ┆ ---        ┆ str        ┆   ┆ ---        ┆ f64        ┆ ---       ┆ ---       │
│     ┆            ┆ str        ┆            ┆   ┆ f64        ┆            ┆ f64       ┆ f64       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 25  ┆ DOUBS      ┆ 25443      ┆ PALANTINE  ┆ … ┆ 0.946069   ┆ 0.006167   ┆ 0.929899  ┆ 0.09306   │
│ 70  ┆ HAUTE-SAON ┆ 70440      ┆ RECOLOGNE  ┆ … ┆ 0.112636   ┆ 0.088098   ┆ 0.355285  ┆ 0.711124  │
│     ┆ E          ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 21  ┆ COTE-D'OR  ┆ 21276      ┆ FONTAINES- ┆ … ┆ 0.043178   ┆ 0.144777   ┆ 0.93831   ┆ 0.18882   │
│     ┆            ┆            ┆ EN-DUESMOI ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ S          ┆   ┆            ┆            ┆           ┆           │
│ 31  ┆ HAUTE-GARO ┆ 31266      ┆ LAHAGE     ┆ … ┆ 0.001752   ┆ 0.149059   ┆ 0.003273  ┆ 0.089764  │
│     ┆ NNE        ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 06  ┆ ALPES-MARI ┆ 06076      ┆ LIEUCHE    ┆ … ┆ 0.509821   ┆ 0.861277   ┆ 0.069635  ┆ 0.323348  │
│     ┆ TIMES      ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ …   ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 23  ┆ CREUSE     ┆ 23231      ┆ SAINT-PIER ┆ … ┆ 0.73475    ┆ 0.980018   ┆ 0.085405  ┆ 0.952224  │
│     ┆            ┆            ┆ RE-DE-FURS ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ AC         ┆   ┆            ┆            ┆           ┆           │
│ 52  ┆ HAUTE-MARN ┆ 52238      ┆ HARRICOURT ┆ … ┆ 0.464339   ┆ 0.898641   ┆ 0.14766   ┆ 0.659091  │
│     ┆ E          ┆            ┆            ┆   ┆            ┆            ┆           ┆           │
│ 48  ┆ LOZERE     ┆ 48049      ┆ CHIRAC     ┆ … ┆ 0.973157   ┆ 0.652919   ┆ 0.783682  ┆ 0.8938641 │
│ 61  ┆ ORNE       ┆ 61205      ┆ HEUGON     ┆ … ┆ 0.493604   ┆ 0.358725   ┆ 0.833193  ┆ 0.591287  │
│ 14  ┆ CALVADOS   ┆ 14470      ┆ NORREY-EN- ┆ … ┆ 0.743903   ┆ 0.446151   ┆ 0.718533  ┆ 0.267685  │
│     ┆            ┆            ┆ BESSIN     ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [138]:
unique_cols = set([col[:-4] for col in socio_economic_data['agesexcommunes'].columns])
print(unique_cols)

{'', 'perpropf', 'poph1539', 'poph014', 'popf60p', 'nomcom', 'no', 'prop60p', 'poph4059', 'poph60p', 'propf1539', 'codecom', 'poph', 'perprop014', 'prop1539', 'popf014', 'perage', 'ageh', 'prop014', 'propf60p', 'agef', 'propf014', 'prop4059', 'perprop60p', 'propf', 'popf', 'popf4059', 'popf1539', 'propf4059', 'age', 'pop'}

In [137]:
socio_economic_data['agesexcommunes'].select(cs.starts_with("poph014"))

shape: (37_985, 63)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ poph01419 ┆ poph01419 ┆ poph01419 ┆ poph01419 ┆ … ┆ poph01420 ┆ poph01420 ┆ poph01420 ┆ poph0142 │
│ 62        ┆ 68        ┆ 75        ┆ 82        ┆   ┆ 19        ┆ 20        ┆ 21        ┆ 022      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 5.0       ┆ 0.0       ┆ 5.0       ┆ 12.0      ┆ … ┆ 30        ┆ 33        ┆ 36        ┆ 39       │
│ 3.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 32.0      ┆ 20.0      ┆ 10.0      ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 6.0       ┆ 12.0      ┆ 10.0      ┆ 12.0      ┆ … ┆ 4         ┆ 3         ┆ 3         ┆ 2        │
│ 1.0       ┆ 0.0       ┆ 0.0       ┆ 4.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 85.0      ┆ 92.0      ┆ 75.0      ┆ 84.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 8.0       ┆ 8.0       ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 84.0      ┆ 108.0     ┆ 55.0      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 50.0      ┆ 72.0      ┆ 20.0      ┆ 8.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 32.0      ┆ 60.0      ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [135]:
out = socio_economic_data['agesexcommunes'].unpivot(
    on=[
        "poph0141962", "poph15391962", "poph40591962", "poph60p1962",
        "popf0141962", "popf15391962", "popf40591962", "popf60p1962",
        "ageh1962", "agef1962",
        "poph0141968", "popf0141968",
        # ... add all time-varying columns here
    ],
    index=["dep", "nomdep", "codecommune", "nomcommune"],
    variable_name="variable",
    value_name="value",
)
print(out)

shape: (455_820, 6)
┌─────┬─────────────────┬─────────────┬────────────────────────┬─────────────┬───────┐
│ dep ┆ nomdep          ┆ codecommune ┆ nomcommune             ┆ variable    ┆ value │
│ --- ┆ ---             ┆ ---         ┆ ---                    ┆ ---         ┆ ---   │
│ str ┆ str             ┆ str         ┆ str                    ┆ str         ┆ f64   │
╞═════╪═════════════════╪═════════════╪════════════════════════╪═════════════╪═══════╡
│ 25  ┆ DOUBS           ┆ 25443       ┆ PALANTINE              ┆ poph0141962 ┆ 5.0   │
│ 70  ┆ HAUTE-SAONE     ┆ 70440       ┆ RECOLOGNE              ┆ poph0141962 ┆ 3.0   │
│ 21  ┆ COTE-D'OR       ┆ 21276       ┆ FONTAINES-EN-DUESMOIS  ┆ poph0141962 ┆ 32.0  │
│ 31  ┆ HAUTE-GARONNE   ┆ 31266       ┆ LAHAGE                 ┆ poph0141962 ┆ 6.0   │
│ 06  ┆ ALPES-MARITIMES ┆ 06076       ┆ LIEUCHE                ┆ poph0141962 ┆ 1.0   │
│ …   ┆ …               ┆ …           ┆ …                      ┆ …           ┆ …     │
│ 23  ┆ CREUSE          ┆ 23231       ┆ SAINT-PIERRE-DE-FURSAC ┆ popf0141968 ┆ 104.0 │
│ 52  ┆ HAUTE-MARNE     ┆ 52238       ┆ HARRICOURT             ┆ popf0141968 ┆ 4.0   │
│ 48  ┆ LOZERE          ┆ 48049       ┆ CHIRAC                 ┆ popf0141968 ┆ 124.0 │
│ 61  ┆ ORNE            ┆ 61205       ┆ HEUGON                 ┆ popf0141968 ┆ 44.0  │
│ 14  ┆ CALVADOS        ┆ 14470       ┆ NORREY-EN-BESSIN       ┆ popf0141968 ┆ 32.0  │
└─────┴─────────────────┴─────────────┴────────────────────────┴─────────────┴───────┘

In [134]:
socio_economic_data['agesexcommunes'].schema

Schema([('dep', String),
        ('nomdep', String),
        ('codecommune', String),
        ('nomcommune', String),
        ('poph0141962', Float64),
        ('poph15391962', Float64),
        ('poph40591962', Float64),
        ('poph60p1962', Float64),
        ('popf0141962', Float64),
        ('popf15391962', Float64),
        ('popf40591962', Float64),
        ('popf60p1962', Float64),
        ('ageh1962', Float64),
        ('agef1962', Float64),
        ('poph0141968', Float64),
        ('popf0141968', Float64),
        ('poph15391968', Float64),
        ('popf15391968', Float64),
        ('poph40591968', Float64),
        ('popf40591968', Float64),
        ('poph60p1968', Float64),
        ('popf60p1968', Float64),
        ('ageh1968', Float64),
        ('agef1968', Float64),
        ('poph0141975', Float64),
        ('popf0141975', Float64),
        ('poph15391975', Float64),
        ('popf15391975', Float64),
        ('poph40591975', Float64),
        ('popf40591975', Float64),
        ('poph60p1975', Float64),
        ('popf60p1975', Float64),
        ('ageh1975', Float64),
        ('agef1975', Float64),
        ('poph0141982', Float64),
        ('popf0141982', Float64),
        ('poph15391982', Float64),
        ('popf15391982', Float64),
        ('poph40591982', Float64),
        ('popf40591982', Float64),
        ('poph60p1982', Float64),
        ('popf60p1982', Float64),
        ('ageh1982', Float64),
        ('agef1982', Float64),
        ('poph0141990', Float64),
        ('popf0141990', Float64),
        ('poph15391990', Float64),
        ('popf15391990', Float64),
        ('poph40591990', Float64),
        ('popf40591990', Float64),
        ('poph60p1990', Float64),
        ('popf60p1990', Float64),
        ('ageh1990', Float64),
        ('agef1990', Float64),
        ('poph0141999', Float64),
        ('popf0141999', Float64),
        ('poph15391999', Float64),
        ('popf15391999', Float64),
        ('poph40591999', Float64),
        ('popf40591999', Float64),
        ('poph60p1999', Float64),
        ('popf60p1999', Float64),
        ('ageh1999', Float64),
        ('agef1999', Float64),
        ('poph0142006', Float64),
        ('popf0142006', Float64),
        ('poph15392006', Float64),
        ('popf15392006', Float64),
        ('poph40592006', Float64),
        ('popf40592006', Float64),
        ('poph60p2006', Float64),
        ('popf60p2006', Float64),
        ('ageh2006', Float64),
        ('agef2006', Float64),
        ('poph0142011', Float64),
        ('popf0142011', Float64),
        ('poph15392011', Float64),
        ('popf15392011', Float64),
        ('poph40592011', Float64),
        ('popf40592011', Float64),
        ('poph60p2011', Float64),
        ('popf60p2011', Float64),
        ('ageh2011', Float64),
        ('agef2011', Float64),
        ('poph0142016', Float64),
        ('popf0142016', Float64),
        ('poph15392016', Float64),
        ('popf15392016', Float64),
        ('poph40592016', Float64),
        ('popf40592016', Float64),
        ('poph60p2016', Float64),
        ('popf60p2016', Float64),
        ('ageh2016', Float64),
        ('agef2016', Float64),
        ('popf0141960', Int64),
        ('popf0141961', Int64),
        ('popf0141963', Float64),
        ('popf0141964', Float64),
        ('popf0141965', Float64),
        ('popf0141966', Float64),
        ('popf0141967', Float64),
        ('popf0141969', Float64),
        ('popf0141970', Float64),
        ('popf0141971', Float64),
        ('popf0141972', Float64),
        ('popf0141973', Float64),
        ('popf0141974', Float64),
        ('popf0141976', Float64),
        ('popf0141977', Float64),
        ('popf0141978', Float64),
        ('popf0141979', Float64),
        ('popf0141980', Float64),
        ('popf0141981', Float64),
        ('popf0141983', Float64),
        ('popf0141984', Float64),
        ('popf0141985', Float64),
        ('popf0141986', Float64),
        ('popf0141987', Float64),
        ('popf0141988', Float64),
        ('popf0141989', Float64),
        ('popf0141991', Float64),
        ('popf0141992', Float64),
        ('popf0141993', Float64),
        ('popf0141994', Float64),
        ('popf0141995', Float64),
        ('popf0141996', Float64),
        ('popf0141997', Float64),
        ('popf0141998', Float64),
        ('popf0142000', Float64),
        ('popf0142001', Float64),
        ('popf0142002', Float64),
        ('popf0142003', Float64),
        ('popf0142004', Float64),
        ('popf0142005', Float64),
        ('popf0142007', Float64),
        ('popf0142008', Float64),
        ('popf0142009', Float64),
        ('popf0142010', Float64),
        ('popf0142012', Float64),
        ('popf0142013', Float64),
        ('popf0142014', Float64),
        ('popf0142015', Float64),
        ('popf0142017', Int64),
        ('popf0142018', Int64),
        ('popf0142019', Int64),
        ('popf0142020', Int64),
        ('popf0142021', Int64),
        ('popf0142022', Int64),
        ('popf15391960', Int64),
        ('popf15391961', Int64),
        ('popf15391963', Float64),
        ('popf15391964', Float64),
        ('popf15391965', Float64),
        ('popf15391966', Float64),
        ('popf15391967', Float64),
        ('popf15391969', Float64),
        ('popf15391970', Float64),
        ('popf15391971', Float64),
        ('popf15391972', Float64),
        ('popf15391973', Float64),
        ('popf15391974', Float64),
        ('popf15391976', Float64),
        ('popf15391977', Float64),
        ('popf15391978', Float64),
        ('popf15391979', Float64),
        ('popf15391980', Float64),
        ('popf15391981', Float64),
        ('popf15391983', Float64),
        ('popf15391984', Float64),
        ('popf15391985', Float64),
        ('popf15391986', Float64),
        ('popf15391987', Float64),
        ('popf15391988', Float64),
        ('popf15391989', Float64),
        ('popf15391991', Float64),
        ('popf15391992', Float64),
        ('popf15391993', Float64),
        ('popf15391994', Float64),
        ('popf15391995', Float64),
        ('popf15391996', Float64),
        ('popf15391997', Float64),
        ('popf15391998', Float64),
        ('popf15392000', Float64),
        ('popf15392001', Float64),
        ('popf15392002', Float64),
        ('popf15392003', Float64),
        ('popf15392004', Float64),
        ('popf15392005', Float64),
        ('popf15392007', Float64),
        ('popf15392008', Float64),
        ('popf15392009', Float64),
        ('popf15392010', Float64),
        ('popf15392012', Float64),
        ('popf15392013', Float64),
        ('popf15392014', Float64),
        ('popf15392015', Float64),
        ('popf15392017', Int64),
        ('popf15392018', Int64),
        ('popf15392019', Int64),
        ('popf15392020', Int64),
        ('popf15392021', Int64),
        ('popf15392022', Int64),
        ('popf40591960', Int64),
        ('popf40591961', Int64),
        ('popf40591963', Float64),
        ('popf40591964', Float64),
        ('popf40591965', Float64),
        ('popf40591966', Float64),
        ('popf40591967', Float64),
        ('popf40591969', Float64),
        ('popf40591970', Float64),
        ('popf40591971', Float64),
        ('popf40591972', Float64),
        ('popf40591973', Float64),
        ('popf40591974', Float64),
        ('popf40591976', Float64),
        ('popf40591977', Float64),
        ('popf40591978', Float64),
        ('popf40591979', Float64),
        ('popf40591980', Float64),
        ('popf40591981', Float64),
        ('popf40591983', Float64),
        ('popf40591984', Float64),
        ('popf40591985', Float64),
        ('popf40591986', Float64),
        ('popf40591987', Float64),
        ('popf40591988', Float64),
        ('popf40591989', Float64),
        ('popf40591991', Float64),
        ('popf40591992', Float64),
        ('popf40591993', Float64),
        ('popf40591994', Float64),
        ('popf40591995', Float64),
        ('popf40591996', Float64),
        ('popf40591997', Float64),
        ('popf40591998', Float64),
        ('popf40592000', Float64),
        ('popf40592001', Float64),
        ('popf40592002', Float64),
        ('popf40592003', Float64),
        ('popf40592004', Float64),
        ('popf40592005', Float64),
        ('popf40592007', Float64),
        ('popf40592008', Float64),
        ('popf40592009', Float64),
        ('popf40592010', Float64),
        ('popf40592012', Float64),
        ('popf40592013', Float64),
        ('popf40592014', Float64),
        ('popf40592015', Float64),
        ('popf40592017', Int64),
        ('popf40592018', Int64),
        ('popf40592019', Int64),
        ('popf40592020', Int64),
        ('popf40592021', Int64),
        ('popf40592022', Int64),
        ('popf60p1960', Int64),
        ('popf60p1961', Int64),
        ('popf60p1963', Float64),
        ('popf60p1964', Float64),
        ('popf60p1965', Float64),
        ('popf60p1966', Float64),
        ('popf60p1967', Float64),
        ('popf60p1969', Float64),
        ('popf60p1970', Float64),
        ('popf60p1971', Float64),
        ('popf60p1972', Float64),
        ('popf60p1973', Float64),
        ('popf60p1974', Float64),
        ('popf60p1976', Float64),
        ('popf60p1977', Float64),
        ('popf60p1978', Float64),
        ('popf60p1979', Float64),
        ('popf60p1980', Float64),
        ('popf60p1981', Float64),
        ('popf60p1983', Float64),
        ('popf60p1984', Float64),
        ('popf60p1985', Float64),
        ('popf60p1986', Float64),
        ('popf60p1987', Float64),
        ('popf60p1988', Float64),
        ('popf60p1989', Float64),
        ('popf60p1991', Float64),
        ('popf60p1992', Float64),
        ('popf60p1993', Float64),
        ('popf60p1994', Float64),
        ('popf60p1995', Float64),
        ('popf60p1996', Float64),
        ('popf60p1997', Float64),
        ('popf60p1998', Float64),
        ('popf60p2000', Float64),
        ('popf60p2001', Float64),
        ('popf60p2002', Float64),
        ('popf60p2003', Float64),
        ('popf60p2004', Float64),
        ('popf60p2005', Float64),
        ('popf60p2007', Float64),
        ('popf60p2008', Float64),
        ('popf60p2009', Float64),
        ('popf60p2010', Float64),
        ('popf60p2012', Float64),
        ('popf60p2013', Float64),
        ('popf60p2014', Float64),
        ('popf60p2015', Float64),
        ('popf60p2017', Int64),
        ('popf60p2018', Int64),
        ('popf60p2019', Int64),
        ('popf60p2020', Int64),
        ('popf60p2021', Int64),
        ('popf60p2022', Int64),
        ('poph0141960', Int64),
        ('poph0141961', Int64),
        ('poph0141963', Float64),
        ('poph0141964', Float64),
        ('poph0141965', Float64),
        ('poph0141966', Float64),
        ('poph0141967', Float64),
        ('poph0141969', Float64),
        ('poph0141970', Float64),
        ('poph0141971', Float64),
        ('poph0141972', Float64),
        ('poph0141973', Float64),
        ('poph0141974', Float64),
        ('poph0141976', Float64),
        ('poph0141977', Float64),
        ('poph0141978', Float64),
        ('poph0141979', Float64),
        ('poph0141980', Float64),
        ('poph0141981', Float64),
        ('poph0141983', Float64),
        ('poph0141984', Float64),
        ('poph0141985', Float64),
        ('poph0141986', Float64),
        ('poph0141987', Float64),
        ('poph0141988', Float64),
        ('poph0141989', Float64),
        ('poph0141991', Float64),
        ('poph0141992', Float64),
        ('poph0141993', Float64),
        ('poph0141994', Float64),
        ('poph0141995', Float64),
        ('poph0141996', Float64),
        ('poph0141997', Float64),
        ('poph0141998', Float64),
        ('poph0142000', Float64),
        ('poph0142001', Float64),
        ('poph0142002', Float64),
        ('poph0142003', Float64),
        ('poph0142004', Float64),
        ('poph0142005', Float64),
        ('poph0142007', Float64),
        ('poph0142008', Float64),
        ('poph0142009', Float64),
        ('poph0142010', Float64),
        ('poph0142012', Float64),
        ('poph0142013', Float64),
        ('poph0142014', Float64),
        ('poph0142015', Float64),
        ('poph0142017', Int64),
        ('poph0142018', Int64),
        ('poph0142019', Int64),
        ('poph0142020', Int64),
        ('poph0142021', Int64),
        ('poph0142022', Int64),
        ('poph15391960', Int64),
        ('poph15391961', Int64),
        ('poph15391963', Float64),
        ('poph15391964', Float64),
        ('poph15391965', Float64),
        ('poph15391966', Float64),
        ('poph15391967', Float64),
        ('poph15391969', Float64),
        ('poph15391970', Float64),
        ('poph15391971', Float64),
        ('poph15391972', Float64),
        ('poph15391973', Float64),
        ('poph15391974', Float64),
        ('poph15391976', Float64),
        ('poph15391977', Float64),
        ('poph15391978', Float64),
        ('poph15391979', Float64),
        ('poph15391980', Float64),
        ('poph15391981', Float64),
        ('poph15391983', Float64),
        ('poph15391984', Float64),
        ('poph15391985', Float64),
        ('poph15391986', Float64),
        ('poph15391987', Float64),
        ('poph15391988', Float64),
        ('poph15391989', Float64),
        ('poph15391991', Float64),
        ('poph15391992', Float64),
        ('poph15391993', Float64),
        ('poph15391994', Float64),
        ('poph15391995', Float64),
        ('poph15391996', Float64),
        ('poph15391997', Float64),
        ('poph15391998', Float64),
        ('poph15392000', Float64),
        ('poph15392001', Float64),
        ('poph15392002', Float64),
        ('poph15392003', Float64),
        ('poph15392004', Float64),
        ('poph15392005', Float64),
        ('poph15392007', Float64),
        ('poph15392008', Float64),
        ('poph15392009', Float64),
        ('poph15392010', Float64),
        ('poph15392012', Float64),
        ('poph15392013', Float64),
        ('poph15392014', Float64),
        ('poph15392015', Float64),
        ('poph15392017', Int64),
        ('poph15392018', Int64),
        ('poph15392019', Int64),
        ('poph15392020', Int64),
        ('poph15392021', Int64),
        ('poph15392022', Int64),
        ('poph40591960', Int64),
        ('poph40591961', Int64),
        ('poph40591963', Float64),
        ('poph40591964', Float64),
        ('poph40591965', Float64),
        ('poph40591966', Float64),
        ('poph40591967', Float64),
        ('poph40591969', Float64),
        ('poph40591970', Float64),
        ('poph40591971', Float64),
        ('poph40591972', Float64),
        ('poph40591973', Float64),
        ('poph40591974', Float64),
        ('poph40591976', Float64),
        ('poph40591977', Float64),
        ('poph40591978', Float64),
        ('poph40591979', Float64),
        ('poph40591980', Float64),
        ('poph40591981', Float64),
        ('poph40591983', Float64),
        ('poph40591984', Float64),
        ('poph40591985', Float64),
        ('poph40591986', Float64),
        ('poph40591987', Float64),
        ('poph40591988', Float64),
        ('poph40591989', Float64),
        ('poph40591991', Float64),
        ('poph40591992', Float64),
        ('poph40591993', Float64),
        ('poph40591994', Float64),
        ('poph40591995', Float64),
        ('poph40591996', Float64),
        ('poph40591997', Float64),
        ('poph40591998', Float64),
        ('poph40592000', Float64),
        ('poph40592001', Float64),
        ('poph40592002', Float64),
        ('poph40592003', Float64),
        ('poph40592004', Float64),
        ('poph40592005', Float64),
        ('poph40592007', Float64),
        ('poph40592008', Float64),
        ('poph40592009', Float64),
        ('poph40592010', Float64),
        ('poph40592012', Float64),
        ('poph40592013', Float64),
        ('poph40592014', Float64),
        ('poph40592015', Float64),
        ('poph40592017', Int64),
        ('poph40592018', Int64),
        ('poph40592019', Int64),
        ('poph40592020', Int64),
        ('poph40592021', Int64),
        ('poph40592022', Int64),
        ('poph60p1960', Int64),
        ('poph60p1961', Int64),
        ('poph60p1963', Float64),
        ('poph60p1964', Float64),
        ('poph60p1965', Float64),
        ('poph60p1966', Float64),
        ('poph60p1967', Float64),
        ('poph60p1969', Float64),
        ('poph60p1970', Float64),
        ('poph60p1971', Float64),
        ('poph60p1972', Float64),
        ('poph60p1973', Float64),
        ('poph60p1974', Float64),
        ('poph60p1976', Float64),
        ('poph60p1977', Float64),
        ('poph60p1978', Float64),
        ('poph60p1979', Float64),
        ('poph60p1980', Float64),
        ('poph60p1981', Float64),
        ('poph60p1983', Float64),
        ('poph60p1984', Float64),
        ('poph60p1985', Float64),
        ('poph60p1986', Float64),
        ('poph60p1987', Float64),
        ('poph60p1988', Float64),
        ('poph60p1989', Float64),
        ('poph60p1991', Float64),
        ('poph60p1992', Float64),
        ('poph60p1993', Float64),
        ('poph60p1994', Float64),
        ('poph60p1995', Float64),
        ('poph60p1996', Float64),
        ('poph60p1997', Float64),
        ('poph60p1998', Float64),
        ('poph60p2000', Float64),
        ('poph60p2001', Float64),
        ('poph60p2002', Float64),
        ('poph60p2003', Float64),
        ('poph60p2004', Float64),
        ('poph60p2005', Float64),
        ('poph60p2007', Float64),
        ('poph60p2008', Float64),
        ('poph60p2009', Float64),
        ('poph60p2010', Float64),
        ('poph60p2012', Float64),
        ('poph60p2013', Float64),
        ('poph60p2014', Float64),
        ('poph60p2015', Float64),
        ('poph60p2017', Int64),
        ('poph60p2018', Int64),
        ('poph60p2019', Int64),
        ('poph60p2020', Int64),
        ('poph60p2021', Int64),
        ('poph60p2022', Int64),
        ('agef1960', Float64),
        ('ageh1960', Float64),
        ('agef1961', Float64),
        ('ageh1961', Float64),
        ('agef1963', Float64),
        ('ageh1963', Float64),
        ('agef1964', Float64),
        ('ageh1964', Float64),
        ('agef1965', Float64),
        ('ageh1965', Float64),
        ('agef1966', Float64),
        ('ageh1966', Float64),
        ('agef1967', Float64),
        ('ageh1967', Float64),
        ('agef1969', Float64),
        ('ageh1969', Float64),
        ('agef1970', Float64),
        ('ageh1970', Float64),
        ('agef1971', Float64),
        ('ageh1971', Float64),
        ('agef1972', Float64),
        ('ageh1972', Float64),
        ('agef1973', Float64),
        ('ageh1973', Float64),
        ('agef1974', Float64),
        ('ageh1974', Float64),
        ('agef1976', Float64),
        ('ageh1976', Float64),
        ('agef1977', Float64),
        ('ageh1977', Float64),
        ('agef1978', Float64),
        ('ageh1978', Float64),
        ('agef1979', Float64),
        ('ageh1979', Float64),
        ('agef1980', Float64),
        ('ageh1980', Float64),
        ('agef1981', Float64),
        ('ageh1981', Float64),
        ('agef1983', Float64),
        ('ageh1983', Float64),
        ('agef1984', Float64),
        ('ageh1984', Float64),
        ('agef1985', Float64),
        ('ageh1985', Float64),
        ('agef1986', Float64),
        ('ageh1986', Float64),
        ('agef1987', Float64),
        ('ageh1987', Float64),
        ('agef1988', Float64),
        ('ageh1988', Float64),
        ('agef1989', Float64),
        ('ageh1989', Float64),
        ('agef1991', Float64),
        ('ageh1991', Float64),
        ('agef1992', Float64),
        ('ageh1992', Float64),
        ('agef1993', Float64),
        ('ageh1993', Float64),
        ('agef1994', Float64),
        ('ageh1994', Float64),
        ('agef1995', Float64),
        ('ageh1995', Float64),
        ('agef1996', Float64),
        ('ageh1996', Float64),
        ('agef1997', Float64),
        ('ageh1997', Float64),